[
[[0 :load] [:void]]
[[0 :initialize] [:void]]
[[0 :init] [:id]]
[[0 :new] [:id]]
[[0 :alloc] [:id]]
[[0 :dealloc] [:void]]
[[0 :finalize] [:void]]
[[0 :copy] [:id]]
[[0 :mutableCopy] [:id]]
[[0 :superclass] [:id]]
[[0 :class] [:id]]
[[1 :instancesRespondToSelector] [:signed-char :selector]]
[[1 :conformsToProtocol] [:signed-char :id]]
[[1 :doesNotRecognizeSelector] [:void :selector]]
[[1 :forwardingTargetForSelector] [:id :selector]]
[[1 :forwardInvocation] [:void :id]]
[[1 :methodSignatureForSelector] [:id :selector]]
[[1 :instanceMethodSignatureForSelector] [:id :selector]]
[[0 :allowsWeakReference] [:signed-char]]
[[0 :retainWeakReference] [:signed-char]]
[[0 :description] [:id]]
[[1 :isSubclassOfClass] [:signed-char :id]]
[[1 :resolveClassMethod] [:signed-char :selector]]
[[1 :resolveInstanceMethod] [:signed-char :selector]]
[[0 :nextObject] [:id]]
[[0 :charValue] [:char]]
[[0 :unsignedCharValue] [:unsigned-char]]
[[0 :shortValue] [:short]]
[[0 :unsignedShortValue] [:unsigned-short]]
[[0 :intValue] [:int]]
[[0 :unsignedIntValue] [:unsigned-int]]
[[0 :longValue] [:long]]
[[0 :unsignedLongValue] [:unsigned-long]]
[[0 :longLongValue] [:long-long]]
[[0 :unsignedLongLongValue] [:unsigned-long-long]]
[[0 :floatValue] [:float]]
[[0 :doubleValue] [:double]]
[[0 :boolValue] [:signed-char]]
[[0 :integerValue] [:long]]
[[0 :unsignedIntegerValue] [:unsigned-long]]
[[0 :stringValue] [:id]]
[[1 :compare] [:long :id]]
[[1 :isEqualToNumber] [:signed-char :id]]
[[1 :descriptionWithLocale] [:id :id]]
[[0 :count] [:unsigned-long]]
[[1 :objectAtIndex] [:id :unsigned-long]]
[[1 :addObject] [:void :id]]
[[2 :insertObject :atIndex] [:void :id :unsigned-long]]
[[0 :removeLastObject] [:void]]
[[1 :removeObjectAtIndex] [:void :unsigned-long]]
[[2 :replaceObjectAtIndex :withObject] [:void :unsigned-long :id]]
[[1 :addObject] [:void :id]]
[[1 :addObject] [:void :id]]
[[0 :drain] [:void]]
[[0 :mainBundle] [:id]]
[[1 :bundleWithPath] [:id :id]]
[[1 :initWithPath] [:id :id]]
[[1 :bundleWithURL] [:id :id]]
[[1 :initWithURL] [:id :id]]
[[1 :bundleForClass] [:id :id]]
[[1 :bundleWithIdentifier] [:id :id]]
[[0 :allBundles] [:id]]
[[0 :allFrameworks] [:id]]
[[0 :load] [:signed-char]]
[[0 :isLoaded] [:signed-char]]
[[0 :unload] [:signed-char]]
[[0 :bundleURL] [:id]]
[[0 :resourceURL] [:id]]
[[0 :executableURL] [:id]]
[[1 :URLForAuxiliaryExecutable] [:id :id]]
[[0 :privateFrameworksURL] [:id]]
[[0 :sharedFrameworksURL] [:id]]
[[0 :sharedSupportURL] [:id]]
[[0 :builtInPlugInsURL] [:id]]
[[0 :appStoreReceiptURL] [:id]]
[[0 :bundlePath] [:id]]
[[0 :resourcePath] [:id]]
[[0 :executablePath] [:id]]
[[1 :pathForAuxiliaryExecutable] [:id :id]]
[[0 :privateFrameworksPath] [:id]]
[[0 :sharedFrameworksPath] [:id]]
[[0 :sharedSupportPath] [:id]]
[[0 :builtInPlugInsPath] [:id]]
[[4 :URLForResource :withExtension :subdirectory :inBundleWithURL] [:id :id :id :id :id]]
[[3 :URLsForResourcesWithExtension :subdirectory :inBundleWithURL] [:id :id :id :id]]
[[2 :URLForResource :withExtension] [:id :id :id]]
[[3 :URLForResource :withExtension :subdirectory] [:id :id :id :id]]
[[4 :URLForResource :withExtension :subdirectory :localization] [:id :id :id :id :id]]
[[2 :URLsForResourcesWithExtension :subdirectory] [:id :id :id]]
[[3 :URLsForResourcesWithExtension :subdirectory :localization] [:id :id :id :id]]
[[3 :pathForResource :ofType :inDirectory] [:id :id :id :id]]
[[2 :pathsForResourcesOfType :inDirectory] [:id :id :id]]
[[2 :pathForResource :ofType] [:id :id :id]]
[[3 :pathForResource :ofType :inDirectory] [:id :id :id :id]]
[[4 :pathForResource :ofType :inDirectory :forLocalization] [:id :id :id :id :id]]
[[2 :pathsForResourcesOfType :inDirectory] [:id :id :id]]
[[3 :pathsForResourcesOfType :inDirectory :forLocalization] [:id :id :id :id]]
[[3 :localizedStringForKey :value :table] [:id :id :id :id]]
[[0 :bundleIdentifier] [:id]]
[[0 :infoDictionary] [:id]]
[[0 :localizedInfoDictionary] [:id]]
[[1 :objectForInfoDictionaryKey] [:id :id]]
[[1 :classNamed] [:id :id]]
[[0 :principalClass] [:id]]
[[0 :localizations] [:id]]
[[0 :preferredLocalizations] [:id]]
[[0 :developmentLocalization] [:id]]
[[1 :preferredLocalizationsFromArray] [:id :id]]
[[2 :preferredLocalizationsFromArray :forPreferences] [:id :id :id]]
[[0 :executableArchitectures] [:id]]
[[0 :timeIntervalSinceReferenceDate] [:double]]
[[0 :currentCalendar] [:id]]
[[0 :autoupdatingCurrentCalendar] [:id]]
[[1 :initWithCalendarIdentifier] [:id :id]]
[[0 :calendarIdentifier] [:id]]
[[1 :setLocale] [:void :id]]
[[0 :locale] [:id]]
[[1 :setTimeZone] [:void :id]]
[[0 :timeZone] [:id]]
[[1 :setFirstWeekday] [:void :unsigned-long]]
[[0 :firstWeekday] [:unsigned-long]]
[[1 :setMinimumDaysInFirstWeek] [:void :unsigned-long]]
[[0 :minimumDaysInFirstWeek] [:unsigned-long]]
[[3 :ordinalityOfUnit :inUnit :forDate] [:unsigned-long :unsigned-long :unsigned-long :id]]
[[1 :dateFromComponents] [:id :id]]
[[2 :components :fromDate] [:id :unsigned-long :id]]
[[3 :dateByAddingComponents :toDate :options] [:id :id :id :unsigned-long]]
[[4 :components :fromDate :toDate :options] [:id :unsigned-long :id :id :unsigned-long]]
[[0 :calendar] [:id]]
[[0 :timeZone] [:id]]
[[0 :era] [:long]]
[[0 :year] [:long]]
[[0 :month] [:long]]
[[0 :day] [:long]]
[[0 :hour] [:long]]
[[0 :minute] [:long]]
[[0 :second] [:long]]
[[0 :week] [:long]]
[[0 :weekday] [:long]]
[[0 :weekdayOrdinal] [:long]]
[[0 :quarter] [:long]]
[[0 :weekOfMonth] [:long]]
[[0 :weekOfYear] [:long]]
[[0 :yearForWeekOfYear] [:long]]
[[0 :isLeapMonth] [:signed-char]]
[[1 :setCalendar] [:void :id]]
[[1 :setTimeZone] [:void :id]]
[[1 :setEra] [:void :long]]
[[1 :setYear] [:void :long]]
[[1 :setMonth] [:void :long]]
[[1 :setDay] [:void :long]]
[[1 :setHour] [:void :long]]
[[1 :setMinute] [:void :long]]
[[1 :setSecond] [:void :long]]
[[1 :setWeek] [:void :long]]
[[1 :setWeekday] [:void :long]]
[[1 :setWeekdayOrdinal] [:void :long]]
[[1 :setQuarter] [:void :long]]
[[1 :setWeekOfMonth] [:void :long]]
[[1 :setWeekOfYear] [:void :long]]
[[1 :setYearForWeekOfYear] [:void :long]]
[[1 :setLeapMonth] [:void :signed-char]]
[[0 :date] [:id]]
[[0 :length] [:unsigned-long]]
[[1 :characterAtIndex] [:unsigned-short :unsigned-long]]
[[0 :controlCharacterSet] [:id]]
[[0 :whitespaceCharacterSet] [:id]]
[[0 :whitespaceAndNewlineCharacterSet] [:id]]
[[0 :decimalDigitCharacterSet] [:id]]
[[0 :letterCharacterSet] [:id]]
[[0 :lowercaseLetterCharacterSet] [:id]]
[[0 :uppercaseLetterCharacterSet] [:id]]
[[0 :nonBaseCharacterSet] [:id]]
[[0 :alphanumericCharacterSet] [:id]]
[[0 :decomposableCharacterSet] [:id]]
[[0 :illegalCharacterSet] [:id]]
[[0 :punctuationCharacterSet] [:id]]
[[0 :capitalizedLetterCharacterSet] [:id]]
[[0 :symbolCharacterSet] [:id]]
[[0 :newlineCharacterSet] [:id]]
[[1 :characterSetWithCharactersInString] [:id :id]]
[[1 :characterSetWithBitmapRepresentation] [:id :id]]
[[1 :characterSetWithContentsOfFile] [:id :id]]
[[1 :characterIsMember] [:signed-char :unsigned-short]]
[[0 :bitmapRepresentation] [:id]]
[[0 :invertedSet] [:id]]
[[1 :longCharacterIsMember] [:signed-char :unsigned-int]]
[[1 :isSupersetOfSet] [:signed-char :id]]
[[1 :hasMemberInPlane] [:signed-char :unsigned-char]]
[[1 :addCharactersInString] [:void :id]]
[[1 :removeCharactersInString] [:void :id]]
[[1 :formUnionWithCharacterSet] [:void :id]]
[[1 :formIntersectionWithCharacterSet] [:void :id]]
[[0 :invert] [:void]]
[[1 :encodeDataObject] [:void :id]]
[[0 :decodeDataObject] [:id]]
[[1 :versionForClassName] [:long :id]]
[[0 :length] [:unsigned-long]]
[[1 :setLength] [:void :unsigned-long]]
[[1 :stringForObjectValue] [:id :id]]
[[2 :attributedStringForObjectValue :withDefaultAttributes] [:id :id :id]]
[[1 :editingStringForObjectValue] [:id :id]]
[[1 :stringFromDate] [:id :id]]
[[1 :dateFromString] [:id :id]]
[[3 :localizedStringFromDate :dateStyle :timeStyle] [:id :id :unsigned-long :unsigned-long]]
[[3 :dateFormatFromTemplate :options :locale] [:id :id :unsigned-long :id]]
[[0 :dateFormat] [:id]]
[[0 :dateStyle] [:unsigned-long]]
[[1 :setDateStyle] [:void :unsigned-long]]
[[0 :timeStyle] [:unsigned-long]]
[[1 :setTimeStyle] [:void :unsigned-long]]
[[0 :locale] [:id]]
[[1 :setLocale] [:void :id]]
[[0 :generatesCalendarDates] [:signed-char]]
[[1 :setGeneratesCalendarDates] [:void :signed-char]]
[[0 :formatterBehavior] [:unsigned-long]]
[[1 :setFormatterBehavior] [:void :unsigned-long]]
[[0 :defaultFormatterBehavior] [:unsigned-long]]
[[1 :setDefaultFormatterBehavior] [:void :unsigned-long]]
[[1 :setDateFormat] [:void :id]]
[[0 :timeZone] [:id]]
[[1 :setTimeZone] [:void :id]]
[[0 :calendar] [:id]]
[[1 :setCalendar] [:void :id]]
[[0 :isLenient] [:signed-char]]
[[1 :setLenient] [:void :signed-char]]
[[0 :twoDigitStartDate] [:id]]
[[1 :setTwoDigitStartDate] [:void :id]]
[[0 :defaultDate] [:id]]
[[1 :setDefaultDate] [:void :id]]
[[0 :eraSymbols] [:id]]
[[1 :setEraSymbols] [:void :id]]
[[0 :monthSymbols] [:id]]
[[1 :setMonthSymbols] [:void :id]]
[[0 :shortMonthSymbols] [:id]]
[[1 :setShortMonthSymbols] [:void :id]]
[[0 :weekdaySymbols] [:id]]
[[1 :setWeekdaySymbols] [:void :id]]
[[0 :shortWeekdaySymbols] [:id]]
[[1 :setShortWeekdaySymbols] [:void :id]]
[[0 :AMSymbol] [:id]]
[[1 :setAMSymbol] [:void :id]]
[[0 :PMSymbol] [:id]]
[[1 :setPMSymbol] [:void :id]]
[[0 :longEraSymbols] [:id]]
[[1 :setLongEraSymbols] [:void :id]]
[[0 :veryShortMonthSymbols] [:id]]
[[1 :setVeryShortMonthSymbols] [:void :id]]
[[0 :standaloneMonthSymbols] [:id]]
[[1 :setStandaloneMonthSymbols] [:void :id]]
[[0 :shortStandaloneMonthSymbols] [:id]]
[[1 :setShortStandaloneMonthSymbols] [:void :id]]
[[0 :veryShortStandaloneMonthSymbols] [:id]]
[[1 :setVeryShortStandaloneMonthSymbols] [:void :id]]
[[0 :veryShortWeekdaySymbols] [:id]]
[[1 :setVeryShortWeekdaySymbols] [:void :id]]
[[0 :standaloneWeekdaySymbols] [:id]]
[[1 :setStandaloneWeekdaySymbols] [:void :id]]
[[0 :shortStandaloneWeekdaySymbols] [:id]]
[[1 :setShortStandaloneWeekdaySymbols] [:void :id]]
[[0 :veryShortStandaloneWeekdaySymbols] [:id]]
[[1 :setVeryShortStandaloneWeekdaySymbols] [:void :id]]
[[0 :quarterSymbols] [:id]]
[[1 :setQuarterSymbols] [:void :id]]
[[0 :shortQuarterSymbols] [:id]]
[[1 :setShortQuarterSymbols] [:void :id]]
[[0 :standaloneQuarterSymbols] [:id]]
[[1 :setStandaloneQuarterSymbols] [:void :id]]
[[0 :shortStandaloneQuarterSymbols] [:id]]
[[1 :setShortStandaloneQuarterSymbols] [:void :id]]
[[0 :gregorianStartDate] [:id]]
[[1 :setGregorianStartDate] [:void :id]]
[[0 :doesRelativeDateFormatting] [:signed-char]]
[[1 :setDoesRelativeDateFormatting] [:void :signed-char]]
[[0 :string] [:id]]
[[0 :scanLocation] [:unsigned-long]]
[[1 :setScanLocation] [:void :unsigned-long]]
[[1 :setCharactersToBeSkipped] [:void :id]]
[[1 :setCaseSensitive] [:void :signed-char]]
[[1 :setLocale] [:void :id]]
[[0 :count] [:unsigned-long]]
[[1 :objectForKey] [:id :id]]
[[0 :keyEnumerator] [:id]]
[[1 :removeObjectForKey] [:void :id]]
[[2 :setObject :forKey] [:void :id :id]]
[[3 :initWithMantissa :exponent :isNegative] [:id :unsigned-long-long :short :signed-char]]
[[1 :initWithString] [:id :id]]
[[2 :initWithString :locale] [:id :id :id]]
[[1 :descriptionWithLocale] [:id :id]]
[[3 :decimalNumberWithMantissa :exponent :isNegative] [:id :unsigned-long-long :short :signed-char]]
[[1 :decimalNumberWithString] [:id :id]]
[[2 :decimalNumberWithString :locale] [:id :id :id]]
[[0 :zero] [:id]]
[[0 :one] [:id]]
[[0 :minimumDecimalNumber] [:id]]
[[0 :maximumDecimalNumber] [:id]]
[[0 :notANumber] [:id]]
[[1 :decimalNumberByAdding] [:id :id]]
[[2 :decimalNumberByAdding :withBehavior] [:id :id :id]]
[[1 :decimalNumberBySubtracting] [:id :id]]
[[2 :decimalNumberBySubtracting :withBehavior] [:id :id :id]]
[[1 :decimalNumberByMultiplyingBy] [:id :id]]
[[2 :decimalNumberByMultiplyingBy :withBehavior] [:id :id :id]]
[[1 :decimalNumberByDividingBy] [:id :id]]
[[2 :decimalNumberByDividingBy :withBehavior] [:id :id :id]]
[[1 :decimalNumberByRaisingToPower] [:id :unsigned-long]]
[[2 :decimalNumberByRaisingToPower :withBehavior] [:id :unsigned-long :id]]
[[1 :decimalNumberByMultiplyingByPowerOf10] [:id :short]]
[[2 :decimalNumberByMultiplyingByPowerOf10 :withBehavior] [:id :short :id]]
[[1 :decimalNumberByRoundingAccordingToBehavior] [:id :id]]
[[1 :compare] [:long :id]]
[[1 :setDefaultBehavior] [:void :id]]
[[0 :defaultBehavior] [:id]]
[[0 :doubleValue] [:double]]
[[0 :defaultDecimalNumberHandler] [:id]]
[[6 :initWithRoundingMode :scale :raiseOnExactness :raiseOnOverflow :raiseOnUnderflow :raiseOnDivideByZero] [:id :unsigned-long :short :signed-char :signed-char :signed-char :signed-char]]
[[6 :decimalNumberHandlerWithRoundingMode :scale :raiseOnExactness :raiseOnOverflow :raiseOnUnderflow :raiseOnDivideByZero] [:id :unsigned-long :short :signed-char :signed-char :signed-char :signed-char]]
[[3 :initWithDomain :code :userInfo] [:id :id :long :id]]
[[3 :errorWithDomain :code :userInfo] [:id :id :long :id]]
[[0 :domain] [:id]]
[[0 :code] [:long]]
[[0 :userInfo] [:id]]
[[0 :localizedDescription] [:id]]
[[0 :localizedFailureReason] [:id]]
[[0 :localizedRecoverySuggestion] [:id]]
[[0 :localizedRecoveryOptions] [:id]]
[[0 :recoveryAttempter] [:id]]
[[0 :helpAnchor] [:id]]
[[3 :exceptionWithName :reason :userInfo] [:id :id :id :id]]
[[3 :initWithName :reason :userInfo] [:id :id :id :id]]
[[0 :name] [:id]]
[[0 :reason] [:id]]
[[0 :userInfo] [:id]]
[[0 :callStackReturnAddresses] [:id]]
[[0 :callStackSymbols] [:id]]
[[0 :raise] [:void]]
[[0 :currentHandler] [:id]]
[[5 :handleFailureInMethod :object :file :lineNumber :description] [:void :selector :id :id :long :id]]
[[4 :handleFailureInFunction :file :lineNumber :description] [:void :id :id :long :id]]
[[0 :availableData] [:id]]
[[0 :readDataToEndOfFile] [:id]]
[[1 :readDataOfLength] [:id :unsigned-long]]
[[1 :writeData] [:void :id]]
[[0 :offsetInFile] [:unsigned-long-long]]
[[0 :seekToEndOfFile] [:unsigned-long-long]]
[[1 :seekToFileOffset] [:void :unsigned-long-long]]
[[1 :truncateFileAtOffset] [:void :unsigned-long-long]]
[[0 :synchronizeFile] [:void]]
[[0 :closeFile] [:void]]
[[0 :fileHandleForReading] [:id]]
[[0 :fileHandleForWriting] [:id]]
[[0 :init] [:id]]
[[0 :pipe] [:id]]
[[0 :defaultManager] [:id]]
[[2 :mountedVolumeURLsIncludingResourceValuesForKeys :options] [:id :id :unsigned-long]]
[[2 :URLsForDirectory :inDomains] [:id :unsigned-long :unsigned-long]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[2 :fileAttributesAtPath :traverseLink] [:id :id :signed-char]]
[[2 :changeFileAttributes :atPath] [:signed-char :id :id]]
[[1 :directoryContentsAtPath] [:id :id]]
[[1 :fileSystemAttributesAtPath] [:id :id]]
[[1 :pathContentOfSymbolicLinkAtPath] [:id :id]]
[[2 :createSymbolicLinkAtPath :pathContent] [:signed-char :id :id]]
[[2 :createDirectoryAtPath :attributes] [:signed-char :id :id]]
[[3 :linkPath :toPath :handler] [:signed-char :id :id :id]]
[[3 :copyPath :toPath :handler] [:signed-char :id :id :id]]
[[3 :movePath :toPath :handler] [:signed-char :id :id :id]]
[[2 :removeFileAtPath :handler] [:signed-char :id :id]]
[[0 :currentDirectoryPath] [:id]]
[[1 :changeCurrentDirectoryPath] [:signed-char :id]]
[[1 :fileExistsAtPath] [:signed-char :id]]
[[1 :isReadableFileAtPath] [:signed-char :id]]
[[1 :isWritableFileAtPath] [:signed-char :id]]
[[1 :isExecutableFileAtPath] [:signed-char :id]]
[[1 :isDeletableFileAtPath] [:signed-char :id]]
[[2 :contentsEqualAtPath :andPath] [:signed-char :id :id]]
[[1 :displayNameAtPath] [:id :id]]
[[1 :componentsToDisplayForPath] [:id :id]]
[[1 :enumeratorAtPath] [:id :id]]
[[1 :subpathsAtPath] [:id :id]]
[[1 :contentsAtPath] [:id :id]]
[[3 :createFileAtPath :contents :attributes] [:signed-char :id :id :id]]
[[1 :isUbiquitousItemAtURL] [:signed-char :id]]
[[1 :URLForUbiquityContainerIdentifier] [:id :id]]
[[0 :ubiquityIdentityToken] [:id]]
[[1 :containerURLForSecurityApplicationGroupIdentifier] [:id :id]]
[[0 :fileAttributes] [:id]]
[[0 :directoryAttributes] [:id]]
[[0 :skipDescendents] [:void]]
[[0 :level] [:unsigned-long]]
[[0 :skipDescendants] [:void]]
[[1 :initWithOptions] [:id :unsigned-long]]
[[1 :pointerFunctionsWithOptions] [:id :unsigned-long]]
[[0 :usesStrongWriteBarrier] [:signed-char]]
[[1 :setUsesStrongWriteBarrier] [:void :signed-char]]
[[0 :usesWeakReadAndWriteBarriers] [:signed-char]]
[[1 :setUsesWeakReadAndWriteBarriers] [:void :signed-char]]
[[2 :initWithOptions :capacity] [:id :unsigned-long :unsigned-long]]
[[2 :initWithPointerFunctions :capacity] [:id :id :unsigned-long]]
[[1 :hashTableWithOptions] [:id :unsigned-long]]
[[0 :hashTableWithWeakObjects] [:id]]
[[0 :weakObjectsHashTable] [:id]]
[[0 :pointerFunctions] [:id]]
[[0 :count] [:unsigned-long]]
[[1 :member] [:id :id]]
[[0 :objectEnumerator] [:id]]
[[1 :addObject] [:void :id]]
[[1 :removeObject] [:void :id]]
[[0 :removeAllObjects] [:void]]
[[0 :allObjects] [:id]]
[[0 :anyObject] [:id]]
[[1 :containsObject] [:signed-char :id]]
[[1 :intersectsHashTable] [:signed-char :id]]
[[1 :isEqualToHashTable] [:signed-char :id]]
[[1 :isSubsetOfHashTable] [:signed-char :id]]
[[1 :intersectHashTable] [:void :id]]
[[1 :unionHashTable] [:void :id]]
[[1 :minusHashTable] [:void :id]]
[[0 :setRepresentation] [:id]]
[[1 :initWithProperties] [:id :id]]
[[1 :cookieWithProperties] [:id :id]]
[[1 :requestHeaderFieldsWithCookies] [:id :id]]
[[2 :cookiesWithResponseHeaderFields :forURL] [:id :id :id]]
[[0 :properties] [:id]]
[[0 :version] [:unsigned-long]]
[[0 :name] [:id]]
[[0 :value] [:id]]
[[0 :expiresDate] [:id]]
[[0 :isSessionOnly] [:signed-char]]
[[0 :domain] [:id]]
[[0 :path] [:id]]
[[0 :isSecure] [:signed-char]]
[[0 :isHTTPOnly] [:signed-char]]
[[0 :comment] [:id]]
[[0 :commentURL] [:id]]
[[0 :portList] [:id]]
[[0 :sharedHTTPCookieStorage] [:id]]
[[0 :cookies] [:id]]
[[1 :setCookie] [:void :id]]
[[1 :deleteCookie] [:void :id]]
[[1 :cookiesForURL] [:id :id]]
[[3 :setCookies :forURL :mainDocumentURL] [:void :id :id :id]]
[[0 :cookieAcceptPolicy] [:unsigned-long]]
[[1 :setCookieAcceptPolicy] [:void :unsigned-long]]
[[1 :sortedCookiesUsingDescriptors] [:id :id]]
[[1 :indexPathWithIndex] [:id :unsigned-long]]
[[1 :initWithIndex] [:id :unsigned-long]]
[[1 :indexPathByAddingIndex] [:id :unsigned-long]]
[[0 :indexPathByRemovingLastIndex] [:id]]
[[1 :indexAtPosition] [:unsigned-long :unsigned-long]]
[[0 :length] [:unsigned-long]]
[[1 :compare] [:long :id]]
[[0 :indexSet] [:id]]
[[1 :indexSetWithIndex] [:id :unsigned-long]]
[[0 :init] [:id]]
[[1 :initWithIndex] [:id :unsigned-long]]
[[1 :initWithIndexSet] [:id :id]]
[[1 :isEqualToIndexSet] [:signed-char :id]]
[[0 :count] [:unsigned-long]]
[[0 :firstIndex] [:unsigned-long]]
[[0 :lastIndex] [:unsigned-long]]
[[1 :indexGreaterThanIndex] [:unsigned-long :unsigned-long]]
[[1 :indexLessThanIndex] [:unsigned-long :unsigned-long]]
[[1 :indexGreaterThanOrEqualToIndex] [:unsigned-long :unsigned-long]]
[[1 :indexLessThanOrEqualToIndex] [:unsigned-long :unsigned-long]]
[[1 :containsIndex] [:signed-char :unsigned-long]]
[[1 :containsIndexes] [:signed-char :id]]
[[1 :addIndexes] [:void :id]]
[[1 :removeIndexes] [:void :id]]
[[0 :removeAllIndexes] [:void]]
[[1 :addIndex] [:void :unsigned-long]]
[[1 :removeIndex] [:void :unsigned-long]]
[[2 :shiftIndexesStartingAtIndex :by] [:void :unsigned-long :long]]
[[1 :invocationWithMethodSignature] [:id :id]]
[[0 :methodSignature] [:id]]
[[0 :retainArguments] [:void]]
[[0 :argumentsRetained] [:signed-char]]
[[0 :target] [:id]]
[[1 :setTarget] [:void :id]]
[[0 :selector] [:selector]]
[[1 :setSelector] [:void :selector]]
[[0 :invoke] [:void]]
[[1 :invokeWithTarget] [:void :id]]
[[1 :isValidJSONObject] [:signed-char :id]]
[[0 :count] [:unsigned-long]]
[[1 :objectAtIndex] [:id :unsigned-long]]
[[1 :indexOfObject] [:unsigned-long :id]]
[[2 :insertObject :atIndex] [:void :id :unsigned-long]]
[[1 :removeObjectAtIndex] [:void :unsigned-long]]
[[2 :replaceObjectAtIndex :withObject] [:void :unsigned-long :id]]
[[0 :count] [:unsigned-long]]
[[1 :member] [:id :id]]
[[0 :objectEnumerator] [:id]]
[[1 :addObject] [:void :id]]
[[1 :removeObject] [:void :id]]
[[1 :initWithCapacity] [:id :unsigned-long]]
[[1 :initWithArray] [:id :id]]
[[1 :initWithSet] [:id :id]]
[[1 :countForObject] [:unsigned-long :id]]
[[0 :objectEnumerator] [:id]]
[[1 :addObject] [:void :id]]
[[1 :removeObject] [:void :id]]
[[2 :propertyList :isValidForFormat] [:signed-char :id :unsigned-long]]
[[1 :archivedDataWithRootObject] [:id :id]]
[[2 :archiveRootObject :toFile] [:signed-char :id :id]]
[[1 :initForWritingWithMutableData] [:id :id]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[1 :setOutputFormat] [:void :unsigned-long]]
[[0 :outputFormat] [:unsigned-long]]
[[0 :finishEncoding] [:void]]
[[2 :setClassName :forClass] [:void :id :id]]
[[2 :setClassName :forClass] [:void :id :id]]
[[1 :classNameForClass] [:id :id]]
[[1 :classNameForClass] [:id :id]]
[[2 :encodeObject :forKey] [:void :id :id]]
[[2 :encodeConditionalObject :forKey] [:void :id :id]]
[[2 :encodeBool :forKey] [:void :signed-char :id]]
[[2 :encodeInt :forKey] [:void :int :id]]
[[2 :encodeInt32 :forKey] [:void :int :id]]
[[2 :encodeInt64 :forKey] [:void :long-long :id]]
[[2 :encodeFloat :forKey] [:void :float :id]]
[[2 :encodeDouble :forKey] [:void :double :id]]
[[1 :unarchiveObjectWithData] [:id :id]]
[[1 :unarchiveObjectWithFile] [:id :id]]
[[1 :initForReadingWithData] [:id :id]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[0 :finishDecoding] [:void]]
[[2 :setClass :forClassName] [:void :id :id]]
[[2 :setClass :forClassName] [:void :id :id]]
[[1 :classForClassName] [:id :id]]
[[1 :classForClassName] [:id :id]]
[[1 :containsValueForKey] [:signed-char :id]]
[[1 :decodeObjectForKey] [:id :id]]
[[1 :decodeBoolForKey] [:signed-char :id]]
[[1 :decodeIntForKey] [:int :id]]
[[1 :decodeInt32ForKey] [:int :id]]
[[1 :decodeInt64ForKey] [:long-long :id]]
[[1 :decodeFloatForKey] [:float :id]]
[[1 :decodeDoubleForKey] [:double :id]]
[[1 :objectForKey] [:id :id]]
[[2 :displayNameForKey :value] [:id :id :id]]
[[0 :tryLock] [:signed-char]]
[[1 :lockBeforeDate] [:signed-char :id]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[1 :initWithCondition] [:id :long]]
[[0 :condition] [:long]]
[[1 :lockWhenCondition] [:void :long]]
[[0 :tryLock] [:signed-char]]
[[1 :tryLockWhenCondition] [:signed-char :long]]
[[1 :unlockWithCondition] [:void :long]]
[[1 :lockBeforeDate] [:signed-char :id]]
[[2 :lockWhenCondition :beforeDate] [:signed-char :long :id]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[0 :tryLock] [:signed-char]]
[[1 :lockBeforeDate] [:signed-char :id]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[0 :wait] [:void]]
[[1 :waitUntilDate] [:signed-char :id]]
[[0 :signal] [:void]]
[[0 :broadcast] [:void]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[3 :initWithKeyOptions :valueOptions :capacity] [:id :unsigned-long :unsigned-long :unsigned-long]]
[[3 :initWithKeyPointerFunctions :valuePointerFunctions :capacity] [:id :id :id :unsigned-long]]
[[2 :mapTableWithKeyOptions :valueOptions] [:id :unsigned-long :unsigned-long]]
[[0 :mapTableWithStrongToStrongObjects] [:id]]
[[0 :mapTableWithWeakToStrongObjects] [:id]]
[[0 :mapTableWithStrongToWeakObjects] [:id]]
[[0 :mapTableWithWeakToWeakObjects] [:id]]
[[0 :strongToStrongObjectsMapTable] [:id]]
[[0 :weakToStrongObjectsMapTable] [:id]]
[[0 :strongToWeakObjectsMapTable] [:id]]
[[0 :weakToWeakObjectsMapTable] [:id]]
[[0 :keyPointerFunctions] [:id]]
[[0 :valuePointerFunctions] [:id]]
[[1 :objectForKey] [:id :id]]
[[1 :removeObjectForKey] [:void :id]]
[[2 :setObject :forKey] [:void :id :id]]
[[0 :count] [:unsigned-long]]
[[0 :keyEnumerator] [:id]]
[[0 :objectEnumerator] [:id]]
[[0 :removeAllObjects] [:void]]
[[0 :dictionaryRepresentation] [:id]]
[[0 :numberOfArguments] [:unsigned-long]]
[[0 :frameLength] [:unsigned-long]]
[[0 :isOneway] [:signed-char]]
[[0 :methodReturnLength] [:unsigned-long]]
[[0 :name] [:id]]
[[0 :object] [:id]]
[[0 :userInfo] [:id]]
[[0 :defaultCenter] [:id]]
[[4 :addObserver :selector :name :object] [:void :id :selector :id :id]]
[[1 :postNotification] [:void :id]]
[[2 :postNotificationName :object] [:void :id :id]]
[[3 :postNotificationName :object :userInfo] [:void :id :id :id]]
[[1 :removeObserver] [:void :id]]
[[3 :removeObserver :name :object] [:void :id :id :id]]
[[0 :defaultQueue] [:id]]
[[1 :initWithNotificationCenter] [:id :id]]
[[2 :enqueueNotification :postingStyle] [:void :id :unsigned-long]]
[[4 :enqueueNotification :postingStyle :coalesceMask :forModes] [:void :id :unsigned-long :unsigned-long :id]]
[[2 :dequeueNotificationsMatching :coalesceMask] [:void :id :unsigned-long]]
[[0 :null] [:id]]
[[1 :stringFromNumber] [:id :id]]
[[1 :numberFromString] [:id :id]]
[[2 :localizedStringFromNumber :numberStyle] [:id :id :unsigned-long]]
[[0 :numberStyle] [:unsigned-long]]
[[1 :setNumberStyle] [:void :unsigned-long]]
[[0 :locale] [:id]]
[[1 :setLocale] [:void :id]]
[[0 :generatesDecimalNumbers] [:signed-char]]
[[1 :setGeneratesDecimalNumbers] [:void :signed-char]]
[[0 :formatterBehavior] [:unsigned-long]]
[[1 :setFormatterBehavior] [:void :unsigned-long]]
[[0 :defaultFormatterBehavior] [:unsigned-long]]
[[1 :setDefaultFormatterBehavior] [:void :unsigned-long]]
[[0 :negativeFormat] [:id]]
[[1 :setNegativeFormat] [:void :id]]
[[0 :textAttributesForNegativeValues] [:id]]
[[1 :setTextAttributesForNegativeValues] [:void :id]]
[[0 :positiveFormat] [:id]]
[[1 :setPositiveFormat] [:void :id]]
[[0 :textAttributesForPositiveValues] [:id]]
[[1 :setTextAttributesForPositiveValues] [:void :id]]
[[0 :allowsFloats] [:signed-char]]
[[1 :setAllowsFloats] [:void :signed-char]]
[[0 :decimalSeparator] [:id]]
[[1 :setDecimalSeparator] [:void :id]]
[[0 :alwaysShowsDecimalSeparator] [:signed-char]]
[[1 :setAlwaysShowsDecimalSeparator] [:void :signed-char]]
[[0 :currencyDecimalSeparator] [:id]]
[[1 :setCurrencyDecimalSeparator] [:void :id]]
[[0 :usesGroupingSeparator] [:signed-char]]
[[1 :setUsesGroupingSeparator] [:void :signed-char]]
[[0 :groupingSeparator] [:id]]
[[1 :setGroupingSeparator] [:void :id]]
[[0 :zeroSymbol] [:id]]
[[1 :setZeroSymbol] [:void :id]]
[[0 :textAttributesForZero] [:id]]
[[1 :setTextAttributesForZero] [:void :id]]
[[0 :nilSymbol] [:id]]
[[1 :setNilSymbol] [:void :id]]
[[0 :textAttributesForNil] [:id]]
[[1 :setTextAttributesForNil] [:void :id]]
[[0 :notANumberSymbol] [:id]]
[[1 :setNotANumberSymbol] [:void :id]]
[[0 :textAttributesForNotANumber] [:id]]
[[1 :setTextAttributesForNotANumber] [:void :id]]
[[0 :positiveInfinitySymbol] [:id]]
[[1 :setPositiveInfinitySymbol] [:void :id]]
[[0 :textAttributesForPositiveInfinity] [:id]]
[[1 :setTextAttributesForPositiveInfinity] [:void :id]]
[[0 :negativeInfinitySymbol] [:id]]
[[1 :setNegativeInfinitySymbol] [:void :id]]
[[0 :textAttributesForNegativeInfinity] [:id]]
[[1 :setTextAttributesForNegativeInfinity] [:void :id]]
[[0 :positivePrefix] [:id]]
[[1 :setPositivePrefix] [:void :id]]
[[0 :positiveSuffix] [:id]]
[[1 :setPositiveSuffix] [:void :id]]
[[0 :negativePrefix] [:id]]
[[1 :setNegativePrefix] [:void :id]]
[[0 :negativeSuffix] [:id]]
[[1 :setNegativeSuffix] [:void :id]]
[[0 :currencyCode] [:id]]
[[1 :setCurrencyCode] [:void :id]]
[[0 :currencySymbol] [:id]]
[[1 :setCurrencySymbol] [:void :id]]
[[0 :internationalCurrencySymbol] [:id]]
[[1 :setInternationalCurrencySymbol] [:void :id]]
[[0 :percentSymbol] [:id]]
[[1 :setPercentSymbol] [:void :id]]
[[0 :perMillSymbol] [:id]]
[[1 :setPerMillSymbol] [:void :id]]
[[0 :minusSign] [:id]]
[[1 :setMinusSign] [:void :id]]
[[0 :plusSign] [:id]]
[[1 :setPlusSign] [:void :id]]
[[0 :exponentSymbol] [:id]]
[[1 :setExponentSymbol] [:void :id]]
[[0 :groupingSize] [:unsigned-long]]
[[1 :setGroupingSize] [:void :unsigned-long]]
[[0 :secondaryGroupingSize] [:unsigned-long]]
[[1 :setSecondaryGroupingSize] [:void :unsigned-long]]
[[0 :multiplier] [:id]]
[[1 :setMultiplier] [:void :id]]
[[0 :formatWidth] [:unsigned-long]]
[[1 :setFormatWidth] [:void :unsigned-long]]
[[0 :paddingCharacter] [:id]]
[[1 :setPaddingCharacter] [:void :id]]
[[0 :paddingPosition] [:unsigned-long]]
[[1 :setPaddingPosition] [:void :unsigned-long]]
[[0 :roundingMode] [:unsigned-long]]
[[1 :setRoundingMode] [:void :unsigned-long]]
[[0 :roundingIncrement] [:id]]
[[1 :setRoundingIncrement] [:void :id]]
[[0 :minimumIntegerDigits] [:unsigned-long]]
[[1 :setMinimumIntegerDigits] [:void :unsigned-long]]
[[0 :maximumIntegerDigits] [:unsigned-long]]
[[1 :setMaximumIntegerDigits] [:void :unsigned-long]]
[[0 :minimumFractionDigits] [:unsigned-long]]
[[1 :setMinimumFractionDigits] [:void :unsigned-long]]
[[0 :maximumFractionDigits] [:unsigned-long]]
[[1 :setMaximumFractionDigits] [:void :unsigned-long]]
[[0 :minimum] [:id]]
[[1 :setMinimum] [:void :id]]
[[0 :maximum] [:id]]
[[1 :setMaximum] [:void :id]]
[[0 :currencyGroupingSeparator] [:id]]
[[1 :setCurrencyGroupingSeparator] [:void :id]]
[[0 :isLenient] [:signed-char]]
[[1 :setLenient] [:void :signed-char]]
[[0 :usesSignificantDigits] [:signed-char]]
[[1 :setUsesSignificantDigits] [:void :signed-char]]
[[0 :minimumSignificantDigits] [:unsigned-long]]
[[1 :setMinimumSignificantDigits] [:void :unsigned-long]]
[[0 :maximumSignificantDigits] [:unsigned-long]]
[[1 :setMaximumSignificantDigits] [:void :unsigned-long]]
[[0 :isPartialStringValidationEnabled] [:signed-char]]
[[1 :setPartialStringValidationEnabled] [:void :signed-char]]
[[0 :init] [:id]]
[[0 :start] [:void]]
[[0 :main] [:void]]
[[0 :isCancelled] [:signed-char]]
[[0 :cancel] [:void]]
[[0 :isExecuting] [:signed-char]]
[[0 :isFinished] [:signed-char]]
[[0 :isConcurrent] [:signed-char]]
[[0 :isReady] [:signed-char]]
[[1 :addDependency] [:void :id]]
[[1 :removeDependency] [:void :id]]
[[0 :dependencies] [:id]]
[[0 :queuePriority] [:long]]
[[1 :setQueuePriority] [:void :long]]
[[0 :waitUntilFinished] [:void]]
[[0 :threadPriority] [:double]]
[[1 :setThreadPriority] [:void :double]]
[[0 :executionBlocks] [:id]]
[[3 :initWithTarget :selector :object] [:id :id :selector :id]]
[[1 :initWithInvocation] [:id :id]]
[[0 :invocation] [:id]]
[[0 :result] [:id]]
[[1 :addOperation] [:void :id]]
[[2 :addOperations :waitUntilFinished] [:void :id :signed-char]]
[[0 :operations] [:id]]
[[0 :operationCount] [:unsigned-long]]
[[0 :maxConcurrentOperationCount] [:long]]
[[1 :setMaxConcurrentOperationCount] [:void :long]]
[[1 :setSuspended] [:void :signed-char]]
[[0 :isSuspended] [:signed-char]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[0 :cancelAllOperations] [:void]]
[[0 :waitUntilAllOperationsAreFinished] [:void]]
[[0 :currentQueue] [:id]]
[[0 :mainQueue] [:id]]
[[0 :dominantScript] [:id]]
[[0 :languageMap] [:id]]
[[1 :initWithOptions] [:id :unsigned-long]]
[[1 :initWithPointerFunctions] [:id :id]]
[[1 :pointerArrayWithOptions] [:id :unsigned-long]]
[[1 :pointerArrayWithPointerFunctions] [:id :id]]
[[0 :pointerFunctions] [:id]]
[[1 :removePointerAtIndex] [:void :unsigned-long]]
[[0 :compact] [:void]]
[[0 :count] [:unsigned-long]]
[[1 :setCount] [:void :unsigned-long]]
[[0 :port] [:id]]
[[0 :invalidate] [:void]]
[[0 :isValid] [:signed-char]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :removeFromRunLoop :forMode] [:void :id :id]]
[[0 :reservedSpaceLength] [:unsigned-long]]
[[4 :sendBeforeDate :components :from :reserved] [:signed-char :id :id :id :unsigned-long]]
[[5 :sendBeforeDate :msgid :components :from :reserved] [:signed-char :id :unsigned-long :id :id :unsigned-long]]
[[3 :addConnection :toRunLoop :forMode] [:void :id :id :id]]
[[3 :removeConnection :fromRunLoop :forMode] [:void :id :id :id]]
[[1 :portWithMachPort] [:id :unsigned-int]]
[[1 :initWithMachPort] [:id :unsigned-int]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[2 :portWithMachPort :options] [:id :unsigned-int :unsigned-long]]
[[2 :initWithMachPort :options] [:id :unsigned-int :unsigned-long]]
[[0 :machPort] [:unsigned-int]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :removeFromRunLoop :forMode] [:void :id :id]]
[[0 :init] [:id]]
[[1 :initWithTCPPort] [:id :unsigned-short]]
[[4 :initWithProtocolFamily :socketType :protocol :address] [:id :int :int :int :id]]
[[4 :initWithProtocolFamily :socketType :protocol :socket] [:id :int :int :int :int]]
[[2 :initRemoteWithTCPPort :host] [:id :unsigned-short :id]]
[[4 :initRemoteWithProtocolFamily :socketType :protocol :address] [:id :int :int :int :id]]
[[0 :protocolFamily] [:int]]
[[0 :socketType] [:int]]
[[0 :protocol] [:int]]
[[0 :address] [:id]]
[[0 :socket] [:int]]
[[0 :processInfo] [:id]]
[[0 :environment] [:id]]
[[0 :arguments] [:id]]
[[0 :hostName] [:id]]
[[0 :processName] [:id]]
[[0 :processIdentifier] [:int]]
[[1 :setProcessName] [:void :id]]
[[0 :globallyUniqueString] [:id]]
[[0 :operatingSystem] [:unsigned-long]]
[[0 :operatingSystemName] [:id]]
[[0 :operatingSystemVersionString] [:id]]
[[0 :processorCount] [:unsigned-long]]
[[0 :activeProcessorCount] [:unsigned-long]]
[[0 :physicalMemory] [:unsigned-long-long]]
[[0 :systemUptime] [:double]]
[[0 :disableSuddenTermination] [:void]]
[[0 :enableSuddenTermination] [:void]]
[[1 :disableAutomaticTermination] [:void :id]]
[[1 :enableAutomaticTermination] [:void :id]]
[[1 :setAutomaticTerminationSupportEnabled] [:void :signed-char]]
[[0 :automaticTerminationSupportEnabled] [:signed-char]]
[[0 :alloc] [:id]]
[[0 :class] [:id]]
[[1 :forwardInvocation] [:void :id]]
[[1 :methodSignatureForSelector] [:id :selector]]
[[0 :dealloc] [:void]]
[[0 :finalize] [:void]]
[[0 :description] [:id]]
[[0 :debugDescription] [:id]]
[[1 :respondsToSelector] [:signed-char :selector]]
[[0 :allowsWeakReference] [:signed-char]]
[[0 :retainWeakReference] [:signed-char]]
[[0 :resultType] [:unsigned-long-long]]
[[1 :escapedPatternForString] [:id :id]]
[[0 :pattern] [:id]]
[[0 :options] [:unsigned-long]]
[[0 :numberOfCaptureGroups] [:unsigned-long]]
[[0 :checkingTypes] [:unsigned-long-long]]
[[0 :currentRunLoop] [:id]]
[[0 :mainRunLoop] [:id]]
[[0 :currentMode] [:id]]
[[2 :addTimer :forMode] [:void :id :id]]
[[2 :addPort :forMode] [:void :id :id]]
[[2 :removePort :forMode] [:void :id :id]]
[[1 :limitDateForMode] [:id :id]]
[[2 :acceptInputForMode :beforeDate] [:void :id :id]]
[[2 :sortDescriptorWithKey :ascending] [:id :id :signed-char]]
[[3 :sortDescriptorWithKey :ascending :selector] [:id :id :signed-char :selector]]
[[2 :initWithKey :ascending] [:id :id :signed-char]]
[[3 :initWithKey :ascending :selector] [:id :id :signed-char :selector]]
[[0 :key] [:id]]
[[0 :ascending] [:signed-char]]
[[0 :selector] [:selector]]
[[2 :compareObject :toObject] [:long :id :id]]
[[0 :reversedSortDescriptor] [:id]]
[[0 :open] [:void]]
[[0 :close] [:void]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[1 :propertyForKey] [:id :id]]
[[2 :setProperty :forKey] [:signed-char :id :id]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :removeFromRunLoop :forMode] [:void :id :id]]
[[0 :streamStatus] [:unsigned-long]]
[[0 :streamError] [:id]]
[[0 :hasBytesAvailable] [:signed-char]]
[[0 :hasSpaceAvailable] [:signed-char]]
[[0 :currentThread] [:id]]
[[3 :detachNewThreadSelector :toTarget :withObject] [:void :selector :id :id]]
[[0 :isMultiThreaded] [:signed-char]]
[[0 :threadDictionary] [:id]]
[[1 :sleepUntilDate] [:void :id]]
[[1 :sleepForTimeInterval] [:void :double]]
[[0 :exit] [:void]]
[[0 :threadPriority] [:double]]
[[1 :setThreadPriority] [:signed-char :double]]
[[0 :threadPriority] [:double]]
[[1 :setThreadPriority] [:void :double]]
[[0 :callStackReturnAddresses] [:id]]
[[0 :callStackSymbols] [:id]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[0 :stackSize] [:unsigned-long]]
[[1 :setStackSize] [:void :unsigned-long]]
[[0 :isMainThread] [:signed-char]]
[[0 :isMainThread] [:signed-char]]
[[0 :mainThread] [:id]]
[[0 :init] [:id]]
[[3 :initWithTarget :selector :object] [:id :id :selector :id]]
[[0 :isExecuting] [:signed-char]]
[[0 :isFinished] [:signed-char]]
[[0 :isCancelled] [:signed-char]]
[[0 :cancel] [:void]]
[[0 :start] [:void]]
[[0 :main] [:void]]
[[0 :name] [:id]]
[[0 :data] [:id]]
[[1 :secondsFromGMTForDate] [:long :id]]
[[1 :abbreviationForDate] [:id :id]]
[[1 :isDaylightSavingTimeForDate] [:signed-char :id]]
[[1 :daylightSavingTimeOffsetForDate] [:double :id]]
[[1 :nextDaylightSavingTimeTransitionAfterDate] [:id :id]]
[[3 :timerWithTimeInterval :invocation :repeats] [:id :double :id :signed-char]]
[[3 :scheduledTimerWithTimeInterval :invocation :repeats] [:id :double :id :signed-char]]
[[5 :timerWithTimeInterval :target :selector :userInfo :repeats] [:id :double :id :selector :id :signed-char]]
[[5 :scheduledTimerWithTimeInterval :target :selector :userInfo :repeats] [:id :double :id :selector :id :signed-char]]
[[6 :initWithFireDate :interval :target :selector :userInfo :repeats] [:id :id :double :id :selector :id :signed-char]]
[[0 :fire] [:void]]
[[0 :fireDate] [:id]]
[[1 :setFireDate] [:void :id]]
[[0 :timeInterval] [:double]]
[[0 :invalidate] [:void]]
[[0 :isValid] [:signed-char]]
[[0 :userInfo] [:id]]
[[1 :registerURLHandleClass] [:void :id]]
[[1 :URLHandleClassForURL] [:id :id]]
[[0 :status] [:unsigned-long]]
[[0 :failureReason] [:id]]
[[1 :addClient] [:void :id]]
[[1 :removeClient] [:void :id]]
[[0 :loadInBackground] [:void]]
[[0 :cancelLoadInBackground] [:void]]
[[0 :resourceData] [:id]]
[[0 :availableResourceData] [:id]]
[[0 :expectedResourceDataSize] [:long-long]]
[[0 :flushCachedData] [:void]]
[[1 :backgroundLoadDidFailWithReason] [:void :id]]
[[2 :didLoadBytes :loadComplete] [:void :id :signed-char]]
[[1 :canInitWithURL] [:signed-char :id]]
[[1 :cachedHandleForURL] [:id :id]]
[[2 :initWithURL :cached] [:id :id :signed-char]]
[[1 :propertyForKey] [:id :id]]
[[1 :propertyForKeyIfAvailable] [:id :id]]
[[2 :writeProperty :forKey] [:signed-char :id :id]]
[[1 :writeData] [:signed-char :id]]
[[0 :loadInForeground] [:id]]
[[0 :beginLoadInBackground] [:void]]
[[0 :endLoadInBackground] [:void]]
[[3 :initWithScheme :host :path] [:id :id :id :id]]
[[2 :initFileURLWithPath :isDirectory] [:id :id :signed-char]]
[[1 :initFileURLWithPath] [:id :id]]
[[2 :fileURLWithPath :isDirectory] [:id :id :signed-char]]
[[1 :fileURLWithPath] [:id :id]]
[[1 :initWithString] [:id :id]]
[[2 :initWithString :relativeToURL] [:id :id :id]]
[[1 :URLWithString] [:id :id]]
[[2 :URLWithString :relativeToURL] [:id :id :id]]
[[0 :absoluteString] [:id]]
[[0 :relativeString] [:id]]
[[0 :baseURL] [:id]]
[[0 :absoluteURL] [:id]]
[[0 :scheme] [:id]]
[[0 :resourceSpecifier] [:id]]
[[0 :host] [:id]]
[[0 :port] [:id]]
[[0 :user] [:id]]
[[0 :password] [:id]]
[[0 :path] [:id]]
[[0 :fragment] [:id]]
[[0 :parameterString] [:id]]
[[0 :query] [:id]]
[[0 :relativePath] [:id]]
[[0 :isFileURL] [:signed-char]]
[[0 :standardizedURL] [:id]]
[[0 :isFileReferenceURL] [:signed-char]]
[[0 :fileReferenceURL] [:id]]
[[0 :filePathURL] [:id]]
[[2 :resourceValuesForKeys :fromBookmarkData] [:id :id :id]]
[[0 :startAccessingSecurityScopedResource] [:signed-char]]
[[0 :stopAccessingSecurityScopedResource] [:void]]
[[6 :initWithProtectionSpace :proposedCredential :previousFailureCount :failureResponse :error :sender] [:id :id :id :long :id :id :id]]
[[2 :initWithAuthenticationChallenge :sender] [:id :id :id]]
[[0 :protectionSpace] [:id]]
[[0 :proposedCredential] [:id]]
[[0 :previousFailureCount] [:long]]
[[0 :failureResponse] [:id]]
[[0 :error] [:id]]
[[0 :sender] [:id]]
[[2 :initWithResponse :data] [:id :id :id]]
[[4 :initWithResponse :data :userInfo :storagePolicy] [:id :id :id :id :unsigned-long]]
[[0 :response] [:id]]
[[0 :data] [:id]]
[[0 :userInfo] [:id]]
[[0 :storagePolicy] [:unsigned-long]]
[[0 :sharedURLCache] [:id]]
[[1 :setSharedURLCache] [:void :id]]
[[3 :initWithMemoryCapacity :diskCapacity :diskPath] [:id :unsigned-long :unsigned-long :id]]
[[1 :cachedResponseForRequest] [:id :id]]
[[2 :storeCachedResponse :forRequest] [:void :id :id]]
[[1 :removeCachedResponseForRequest] [:void :id]]
[[0 :removeAllCachedResponses] [:void]]
[[0 :memoryCapacity] [:unsigned-long]]
[[0 :diskCapacity] [:unsigned-long]]
[[1 :setMemoryCapacity] [:void :unsigned-long]]
[[1 :setDiskCapacity] [:void :unsigned-long]]
[[0 :currentMemoryUsage] [:unsigned-long]]
[[0 :currentDiskUsage] [:unsigned-long]]
[[3 :initWithRequest :delegate :startImmediately] [:id :id :id :signed-char]]
[[2 :initWithRequest :delegate] [:id :id :id]]
[[2 :connectionWithRequest :delegate] [:id :id :id]]
[[0 :originalRequest] [:id]]
[[0 :currentRequest] [:id]]
[[0 :start] [:void]]
[[0 :cancel] [:void]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :unscheduleFromRunLoop :forMode] [:void :id :id]]
[[1 :setDelegateQueue] [:void :id]]
[[1 :canHandleRequest] [:signed-char :id]]
[[0 :persistence] [:unsigned-long]]
[[0 :sharedCredentialStorage] [:id]]
[[1 :credentialsForProtectionSpace] [:id :id]]
[[0 :allCredentials] [:id]]
[[2 :setCredential :forProtectionSpace] [:void :id :id]]
[[2 :removeCredential :forProtectionSpace] [:void :id :id]]
[[1 :defaultCredentialForProtectionSpace] [:id :id]]
[[2 :setDefaultCredential :forProtectionSpace] [:void :id :id]]
[[5 :initWithHost :port :protocol :realm :authenticationMethod] [:id :id :long :id :id :id]]
[[5 :initWithProxyHost :port :type :realm :authenticationMethod] [:id :id :long :id :id :id]]
[[0 :realm] [:id]]
[[0 :receivesCredentialSecurely] [:signed-char]]
[[0 :isProxy] [:signed-char]]
[[0 :host] [:id]]
[[0 :port] [:long]]
[[0 :proxyType] [:id]]
[[0 :protocol] [:id]]
[[0 :authenticationMethod] [:id]]
[[3 :initWithRequest :cachedResponse :client] [:id :id :id :id]]
[[0 :client] [:id]]
[[0 :request] [:id]]
[[0 :cachedResponse] [:id]]
[[1 :canInitWithRequest] [:signed-char :id]]
[[1 :canonicalRequestForRequest] [:id :id]]
[[2 :requestIsCacheEquivalent :toRequest] [:signed-char :id :id]]
[[0 :startLoading] [:void]]
[[0 :stopLoading] [:void]]
[[2 :propertyForKey :inRequest] [:id :id :id]]
[[3 :setProperty :forKey :inRequest] [:void :id :id :id]]
[[2 :removePropertyForKey :inRequest] [:void :id :id]]
[[1 :registerClass] [:signed-char :id]]
[[1 :unregisterClass] [:void :id]]
[[1 :requestWithURL] [:id :id]]
[[3 :requestWithURL :cachePolicy :timeoutInterval] [:id :id :unsigned-long :double]]
[[1 :initWithURL] [:id :id]]
[[3 :initWithURL :cachePolicy :timeoutInterval] [:id :id :unsigned-long :double]]
[[0 :URL] [:id]]
[[0 :cachePolicy] [:unsigned-long]]
[[0 :timeoutInterval] [:double]]
[[0 :mainDocumentURL] [:id]]
[[0 :networkServiceType] [:unsigned-long]]
[[0 :allowsCellularAccess] [:signed-char]]
[[1 :setURL] [:void :id]]
[[1 :setCachePolicy] [:void :unsigned-long]]
[[1 :setTimeoutInterval] [:void :double]]
[[1 :setMainDocumentURL] [:void :id]]
[[1 :setNetworkServiceType] [:void :unsigned-long]]
[[1 :setAllowsCellularAccess] [:void :signed-char]]
[[4 :initWithURL :MIMEType :expectedContentLength :textEncodingName] [:id :id :id :long :id]]
[[0 :URL] [:id]]
[[0 :MIMEType] [:id]]
[[0 :expectedContentLength] [:long-long]]
[[0 :textEncodingName] [:id]]
[[0 :suggestedFilename] [:id]]
[[4 :initWithURL :statusCode :HTTPVersion :headerFields] [:id :id :long :id :id]]
[[0 :statusCode] [:long]]
[[0 :allHeaderFields] [:id]]
[[1 :localizedStringForStatusCode] [:id :long]]
[[0 :standardUserDefaults] [:id]]
[[0 :resetStandardUserDefaults] [:void]]
[[0 :init] [:id]]
[[1 :initWithUser] [:id :id]]
[[1 :objectForKey] [:id :id]]
[[2 :setObject :forKey] [:void :id :id]]
[[1 :removeObjectForKey] [:void :id]]
[[1 :stringForKey] [:id :id]]
[[1 :arrayForKey] [:id :id]]
[[1 :dictionaryForKey] [:id :id]]
[[1 :dataForKey] [:id :id]]
[[1 :stringArrayForKey] [:id :id]]
[[1 :integerForKey] [:long :id]]
[[1 :floatForKey] [:float :id]]
[[1 :doubleForKey] [:double :id]]
[[1 :boolForKey] [:signed-char :id]]
[[1 :URLForKey] [:id :id]]
[[2 :setInteger :forKey] [:void :long :id]]
[[2 :setFloat :forKey] [:void :float :id]]
[[2 :setDouble :forKey] [:void :double :id]]
[[2 :setBool :forKey] [:void :signed-char :id]]
[[2 :setURL :forKey] [:void :id :id]]
[[1 :registerDefaults] [:void :id]]
[[1 :addSuiteNamed] [:void :id]]
[[1 :removeSuiteNamed] [:void :id]]
[[0 :dictionaryRepresentation] [:id]]
[[0 :volatileDomainNames] [:id]]
[[1 :volatileDomainForName] [:id :id]]
[[2 :setVolatileDomain :forName] [:void :id :id]]
[[1 :removeVolatileDomainForName] [:void :id]]
[[0 :persistentDomainNames] [:id]]
[[1 :persistentDomainForName] [:id :id]]
[[2 :setPersistentDomain :forName] [:void :id :id]]
[[1 :removePersistentDomainForName] [:void :id]]
[[0 :synchronize] [:signed-char]]
[[1 :objectIsForcedForKey] [:signed-char :id]]
[[2 :objectIsForcedForKey :inDomain] [:signed-char :id :id]]
[[2 :setValueTransformer :forName] [:void :id :id]]
[[1 :valueTransformerForName] [:id :id]]
[[0 :valueTransformerNames] [:id]]
[[0 :transformedValueClass] [:id]]
[[0 :allowsReverseTransformation] [:signed-char]]
[[1 :transformedValue] [:id :id]]
[[1 :reverseTransformedValue] [:id :id]]
[[1 :initWithContentsOfURL] [:id :id]]
[[1 :initWithData] [:id :id]]
[[1 :initWithStream] [:id :id]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[1 :setShouldProcessNamespaces] [:void :signed-char]]
[[1 :setShouldReportNamespacePrefixes] [:void :signed-char]]
[[1 :setShouldResolveExternalEntities] [:void :signed-char]]
[[0 :shouldProcessNamespaces] [:signed-char]]
[[0 :shouldReportNamespacePrefixes] [:signed-char]]
[[0 :shouldResolveExternalEntities] [:signed-char]]
[[0 :parse] [:signed-char]]
[[0 :abortParsing] [:void]]
[[0 :parserError] [:id]]
[[0 :string] [:id]]
[[2 :stringFromByteCount :countStyle] [:id :long-long :long]]
[[1 :stringFromByteCount] [:id :long-long]]
[[0 :allowedUnits] [:unsigned-long]]
[[1 :setAllowedUnits] [:void :unsigned-long]]
[[0 :countStyle] [:long]]
[[1 :setCountStyle] [:void :long]]
[[0 :allowsNonnumericFormatting] [:signed-char]]
[[1 :setAllowsNonnumericFormatting] [:void :signed-char]]
[[0 :includesUnit] [:signed-char]]
[[1 :setIncludesUnit] [:void :signed-char]]
[[0 :includesCount] [:signed-char]]
[[1 :setIncludesCount] [:void :signed-char]]
[[0 :includesActualByteCount] [:signed-char]]
[[1 :setIncludesActualByteCount] [:void :signed-char]]
[[0 :isAdaptive] [:signed-char]]
[[1 :setAdaptive] [:void :signed-char]]
[[0 :zeroPadsFractionDigits] [:signed-char]]
[[1 :setZeroPadsFractionDigits] [:void :signed-char]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[1 :objectForKey] [:id :id]]
[[2 :setObject :forKey] [:void :id :id]]
[[3 :setObject :forKey :cost] [:void :id :id :unsigned-long]]
[[1 :removeObjectForKey] [:void :id]]
[[0 :removeAllObjects] [:void]]
[[1 :setTotalCostLimit] [:void :unsigned-long]]
[[0 :totalCostLimit] [:unsigned-long]]
[[1 :setCountLimit] [:void :unsigned-long]]
[[0 :countLimit] [:unsigned-long]]
[[0 :evictsObjectsWithDiscardedContent] [:signed-char]]
[[1 :setEvictsObjectsWithDiscardedContent] [:void :signed-char]]
[[2 :predicateWithFormat :argumentArray] [:id :id :id]]
[[1 :predicateWithFormat] [:id :id]]
[[1 :predicateWithValue] [:id :signed-char]]
[[0 :predicateFormat] [:id]]
[[1 :predicateWithSubstitutionVariables] [:id :id]]
[[1 :evaluateWithObject] [:signed-char :id]]
[[2 :evaluateWithObject :substitutionVariables] [:signed-char :id :id]]
[[5 :predicateWithLeftExpression :rightExpression :modifier :type :options] [:id :id :id :unsigned-long :unsigned-long :unsigned-long]]
[[3 :predicateWithLeftExpression :rightExpression :customSelector] [:id :id :id :selector]]
[[5 :initWithLeftExpression :rightExpression :modifier :type :options] [:id :id :id :unsigned-long :unsigned-long :unsigned-long]]
[[3 :initWithLeftExpression :rightExpression :customSelector] [:id :id :id :selector]]
[[0 :predicateOperatorType] [:unsigned-long]]
[[0 :comparisonPredicateModifier] [:unsigned-long]]
[[0 :leftExpression] [:id]]
[[0 :rightExpression] [:id]]
[[0 :customSelector] [:selector]]
[[0 :options] [:unsigned-long]]
[[2 :initWithType :subpredicates] [:id :unsigned-long :id]]
[[0 :compoundPredicateType] [:unsigned-long]]
[[0 :subpredicates] [:id]]
[[1 :andPredicateWithSubpredicates] [:id :id]]
[[1 :orPredicateWithSubpredicates] [:id :id]]
[[1 :notPredicateWithSubpredicate] [:id :id]]
[[2 :expressionWithFormat :argumentArray] [:id :id :id]]
[[1 :expressionWithFormat] [:id :id]]
[[1 :expressionForConstantValue] [:id :id]]
[[0 :expressionForEvaluatedObject] [:id]]
[[1 :expressionForVariable] [:id :id]]
[[1 :expressionForKeyPath] [:id :id]]
[[2 :expressionForFunction :arguments] [:id :id :id]]
[[1 :expressionForAggregate] [:id :id]]
[[2 :expressionForUnionSet :with] [:id :id :id]]
[[2 :expressionForIntersectSet :with] [:id :id :id]]
[[2 :expressionForMinusSet :with] [:id :id :id]]
[[3 :expressionForSubquery :usingIteratorVariable :predicate] [:id :id :id :id]]
[[3 :expressionForFunction :selectorName :arguments] [:id :id :id :id]]
[[1 :initWithExpressionType] [:id :unsigned-long]]
[[0 :expressionType] [:unsigned-long]]
[[0 :constantValue] [:id]]
[[0 :keyPath] [:id]]
[[0 :function] [:id]]
[[0 :variable] [:id]]
[[0 :operand] [:id]]
[[0 :arguments] [:id]]
[[0 :collection] [:id]]
[[0 :predicate] [:id]]
[[0 :leftExpression] [:id]]
[[0 :rightExpression] [:id]]
[[2 :expressionValueWithObject :context] [:id :id :id]]
[[1 :addFilePresenter] [:void :id]]
[[1 :removeFilePresenter] [:void :id]]
[[0 :filePresenters] [:id]]
[[1 :initWithFilePresenter] [:id :id]]
[[2 :itemAtURL :willMoveToURL] [:void :id :id]]
[[2 :itemAtURL :didMoveToURL] [:void :id :id]]
[[0 :cancel] [:void]]
[[1 :currentVersionOfItemAtURL] [:id :id]]
[[1 :otherVersionsOfItemAtURL] [:id :id]]
[[1 :unresolvedConflictVersionsOfItemAtURL] [:id :id]]
[[2 :versionOfItemAtURL :forPersistentIdentifier] [:id :id :id]]
[[1 :temporaryDirectoryURLForNewVersionOfItemAtURL] [:id :id]]
[[0 :URL] [:id]]
[[0 :localizedName] [:id]]
[[0 :localizedNameOfSavingComputer] [:id]]
[[0 :modificationDate] [:id]]
[[0 :persistentIdentifier] [:id]]
[[0 :isConflict] [:signed-char]]
[[0 :isResolved] [:signed-char]]
[[1 :setResolved] [:void :signed-char]]
[[0 :isDiscardable] [:signed-char]]
[[1 :setDiscardable] [:void :signed-char]]
[[1 :initDirectoryWithFileWrappers] [:id :id]]
[[1 :initRegularFileWithContents] [:id :id]]
[[1 :initSymbolicLinkWithDestinationURL] [:id :id]]
[[1 :initWithSerializedRepresentation] [:id :id]]
[[0 :isDirectory] [:signed-char]]
[[0 :isRegularFile] [:signed-char]]
[[0 :isSymbolicLink] [:signed-char]]
[[1 :setPreferredFilename] [:void :id]]
[[0 :preferredFilename] [:id]]
[[1 :setFilename] [:void :id]]
[[0 :filename] [:id]]
[[1 :setFileAttributes] [:void :id]]
[[0 :fileAttributes] [:id]]
[[1 :matchesContentsOfURL] [:signed-char :id]]
[[0 :serializedRepresentation] [:id]]
[[1 :addFileWrapper] [:id :id]]
[[2 :addRegularFileWithContents :preferredFilename] [:id :id :id]]
[[1 :removeFileWrapper] [:void :id]]
[[0 :fileWrappers] [:id]]
[[1 :keyForFileWrapper] [:id :id]]
[[0 :regularFileContents] [:id]]
[[0 :symbolicLinkDestinationURL] [:id]]
[[2 :initWithTagSchemes :options] [:id :id :unsigned-long]]
[[0 :tagSchemes] [:id]]
[[1 :setString] [:void :id]]
[[0 :string] [:id]]
[[1 :availableTagSchemesForLanguage] [:id :id]]
[[0 :init] [:id]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[0 :predicate] [:id]]
[[1 :setPredicate] [:void :id]]
[[0 :sortDescriptors] [:id]]
[[1 :setSortDescriptors] [:void :id]]
[[0 :valueListAttributes] [:id]]
[[1 :setValueListAttributes] [:void :id]]
[[0 :groupingAttributes] [:id]]
[[1 :setGroupingAttributes] [:void :id]]
[[0 :notificationBatchingInterval] [:double]]
[[1 :setNotificationBatchingInterval] [:void :double]]
[[0 :searchScopes] [:id]]
[[1 :setSearchScopes] [:void :id]]
[[0 :startQuery] [:signed-char]]
[[0 :stopQuery] [:void]]
[[0 :isStarted] [:signed-char]]
[[0 :isGathering] [:signed-char]]
[[0 :isStopped] [:signed-char]]
[[0 :disableUpdates] [:void]]
[[0 :enableUpdates] [:void]]
[[0 :resultCount] [:unsigned-long]]
[[1 :resultAtIndex] [:id :unsigned-long]]
[[0 :results] [:id]]
[[1 :indexOfResult] [:unsigned-long :id]]
[[0 :valueLists] [:id]]
[[0 :groupedResults] [:id]]
[[2 :valueOfAttribute :forResultAtIndex] [:id :id :unsigned-long]]
[[1 :valueForAttribute] [:id :id]]
[[1 :valuesForAttributes] [:id :id]]
[[0 :attributes] [:id]]
[[0 :attribute] [:id]]
[[0 :value] [:id]]
[[0 :count] [:unsigned-long]]
[[0 :attribute] [:id]]
[[0 :value] [:id]]
[[0 :subgroups] [:id]]
[[0 :resultCount] [:unsigned-long]]
[[1 :resultAtIndex] [:id :unsigned-long]]
[[0 :results] [:id]]
[[4 :initWithDomain :type :name :port] [:id :id :id :id :int]]
[[3 :initWithDomain :type :name] [:id :id :id :id]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :removeFromRunLoop :forMode] [:void :id :id]]
[[0 :domain] [:id]]
[[0 :type] [:id]]
[[0 :name] [:id]]
[[0 :addresses] [:id]]
[[0 :port] [:long]]
[[0 :publish] [:void]]
[[1 :publishWithOptions] [:void :unsigned-long]]
[[0 :resolve] [:void]]
[[0 :stop] [:void]]
[[1 :dictionaryFromTXTRecordData] [:id :id]]
[[1 :dataFromTXTRecordDictionary] [:id :id]]
[[0 :hostName] [:id]]
[[1 :resolveWithTimeout] [:void :double]]
[[1 :setTXTRecordData] [:signed-char :id]]
[[0 :TXTRecordData] [:id]]
[[0 :startMonitoring] [:void]]
[[0 :stopMonitoring] [:void]]
[[0 :init] [:id]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[2 :scheduleInRunLoop :forMode] [:void :id :id]]
[[2 :removeFromRunLoop :forMode] [:void :id :id]]
[[0 :searchForBrowsableDomains] [:void]]
[[0 :searchForRegistrationDomains] [:void]]
[[2 :searchForServicesOfType :inDomain] [:void :id :id]]
[[0 :stop] [:void]]
[[0 :defaultStore] [:id]]
[[1 :objectForKey] [:id :id]]
[[2 :setObject :forKey] [:void :id :id]]
[[1 :removeObjectForKey] [:void :id]]
[[1 :stringForKey] [:id :id]]
[[1 :arrayForKey] [:id :id]]
[[1 :dictionaryForKey] [:id :id]]
[[1 :dataForKey] [:id :id]]
[[1 :longLongForKey] [:long-long :id]]
[[1 :doubleForKey] [:double :id]]
[[1 :boolForKey] [:signed-char :id]]
[[2 :setString :forKey] [:void :id :id]]
[[2 :setData :forKey] [:void :id :id]]
[[2 :setArray :forKey] [:void :id :id]]
[[2 :setDictionary :forKey] [:void :id :id]]
[[2 :setLongLong :forKey] [:void :long-long :id]]
[[2 :setDouble :forKey] [:void :double :id]]
[[2 :setBool :forKey] [:void :signed-char :id]]
[[0 :dictionaryRepresentation] [:id]]
[[0 :synchronize] [:signed-char]]
[[0 :beginUndoGrouping] [:void]]
[[0 :endUndoGrouping] [:void]]
[[0 :groupingLevel] [:long]]
[[0 :disableUndoRegistration] [:void]]
[[0 :enableUndoRegistration] [:void]]
[[0 :isUndoRegistrationEnabled] [:signed-char]]
[[0 :groupsByEvent] [:signed-char]]
[[1 :setGroupsByEvent] [:void :signed-char]]
[[1 :setLevelsOfUndo] [:void :unsigned-long]]
[[0 :levelsOfUndo] [:unsigned-long]]
[[1 :setRunLoopModes] [:void :id]]
[[0 :runLoopModes] [:id]]
[[0 :undo] [:void]]
[[0 :redo] [:void]]
[[0 :undoNestedGroup] [:void]]
[[0 :canUndo] [:signed-char]]
[[0 :canRedo] [:signed-char]]
[[0 :isUndoing] [:signed-char]]
[[0 :isRedoing] [:signed-char]]
[[0 :removeAllActions] [:void]]
[[1 :removeAllActionsWithTarget] [:void :id]]
[[3 :registerUndoWithTarget :selector :object] [:void :id :selector :id]]
[[1 :prepareWithInvocationTarget] [:id :id]]
[[1 :setActionIsDiscardable] [:void :signed-char]]
[[0 :undoActionIsDiscardable] [:signed-char]]
[[0 :redoActionIsDiscardable] [:signed-char]]
[[0 :undoActionName] [:id]]
[[0 :redoActionName] [:id]]
[[1 :setActionName] [:void :id]]
[[0 :undoMenuItemTitle] [:id]]
[[0 :redoMenuItemTitle] [:id]]
[[1 :undoMenuTitleForUndoActionName] [:id :id]]
[[1 :redoMenuTitleForUndoActionName] [:id :id]]
[[0 :UUID] [:id]]
[[0 :init] [:id]]
[[1 :initWithUUIDString] [:id :id]]
[[0 :UUIDString] [:id]]
[[1 :initForWritingWithMutableData] [:id :id]]
[[0 :archiverData] [:id]]
[[1 :encodeRootObject] [:void :id]]
[[1 :encodeConditionalObject] [:void :id]]
[[1 :archivedDataWithRootObject] [:id :id]]
[[2 :archiveRootObject :toFile] [:signed-char :id :id]]
[[2 :encodeClassName :intoClassName] [:void :id :id]]
[[1 :classNameEncodedForTrueClassName] [:id :id]]
[[2 :replaceObject :withObject] [:void :id :id]]
[[1 :initForReadingWithData] [:id :id]]
[[0 :isAtEnd] [:signed-char]]
[[0 :systemVersion] [:unsigned-int]]
[[1 :unarchiveObjectWithData] [:id :id]]
[[1 :unarchiveObjectWithFile] [:id :id]]
[[2 :decodeClassName :asClassName] [:void :id :id]]
[[2 :decodeClassName :asClassName] [:void :id :id]]
[[1 :classNameDecodedForArchiveClassName] [:id :id]]
[[1 :classNameDecodedForArchiveClassName] [:id :id]]
[[2 :replaceObject :withObject] [:void :id :id]]
[[0 :calendarDate] [:id]]
[[3 :dateWithString :calendarFormat :locale] [:id :id :id :id]]
[[2 :dateWithString :calendarFormat] [:id :id :id]]
[[7 :dateWithYear :month :day :hour :minute :second :timeZone] [:id :long :unsigned-long :unsigned-long :unsigned-long :unsigned-long :unsigned-long :id]]
[[6 :dateByAddingYears :months :days :hours :minutes :seconds] [:id :long :long :long :long :long :long]]
[[0 :dayOfCommonEra] [:long]]
[[0 :dayOfMonth] [:long]]
[[0 :dayOfWeek] [:long]]
[[0 :dayOfYear] [:long]]
[[0 :hourOfDay] [:long]]
[[0 :minuteOfHour] [:long]]
[[0 :monthOfYear] [:long]]
[[0 :secondOfMinute] [:long]]
[[0 :yearOfCommonEra] [:long]]
[[0 :calendarFormat] [:id]]
[[2 :descriptionWithCalendarFormat :locale] [:id :id :id]]
[[1 :descriptionWithCalendarFormat] [:id :id]]
[[1 :descriptionWithLocale] [:id :id]]
[[0 :timeZone] [:id]]
[[3 :initWithString :calendarFormat :locale] [:id :id :id :id]]
[[2 :initWithString :calendarFormat] [:id :id :id]]
[[1 :initWithString] [:id :id]]
[[7 :initWithYear :month :day :hour :minute :second :timeZone] [:id :long :unsigned-long :unsigned-long :unsigned-long :unsigned-long :unsigned-long :id]]
[[1 :setCalendarFormat] [:void :id]]
[[1 :setTimeZone] [:void :id]]
[[0 :statistics] [:id]]
[[0 :allConnections] [:id]]
[[0 :defaultConnection] [:id]]
[[2 :connectionWithRegisteredName :host] [:id :id :id]]
[[3 :connectionWithRegisteredName :host :usingNameServer] [:id :id :id :id]]
[[2 :rootProxyForConnectionWithRegisteredName :host] [:id :id :id]]
[[3 :rootProxyForConnectionWithRegisteredName :host :usingNameServer] [:id :id :id :id]]
[[3 :serviceConnectionWithName :rootObject :usingNameServer] [:id :id :id :id]]
[[2 :serviceConnectionWithName :rootObject] [:id :id :id]]
[[1 :setRequestTimeout] [:void :double]]
[[0 :requestTimeout] [:double]]
[[1 :setReplyTimeout] [:void :double]]
[[0 :replyTimeout] [:double]]
[[1 :setRootObject] [:void :id]]
[[0 :rootObject] [:id]]
[[0 :rootProxy] [:id]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[1 :setIndependentConversationQueueing] [:void :signed-char]]
[[0 :independentConversationQueueing] [:signed-char]]
[[0 :isValid] [:signed-char]]
[[0 :invalidate] [:void]]
[[1 :addRequestMode] [:void :id]]
[[1 :removeRequestMode] [:void :id]]
[[0 :requestModes] [:id]]
[[1 :registerName] [:signed-char :id]]
[[2 :registerName :withNameServer] [:signed-char :id :id]]
[[2 :connectionWithReceivePort :sendPort] [:id :id :id]]
[[0 :currentConversation] [:id]]
[[2 :initWithReceivePort :sendPort] [:id :id :id]]
[[0 :sendPort] [:id]]
[[0 :receivePort] [:id]]
[[0 :enableMultipleThreads] [:void]]
[[0 :multipleThreadsEnabled] [:signed-char]]
[[1 :addRunLoop] [:void :id]]
[[1 :removeRunLoop] [:void :id]]
[[0 :runInNewThread] [:void]]
[[0 :remoteObjects] [:id]]
[[0 :localObjects] [:id]]
[[1 :dispatchWithComponents] [:void :id]]
[[0 :invocation] [:id]]
[[0 :connection] [:id]]
[[0 :conversation] [:id]]
[[1 :replyWithException] [:void :id]]
[[2 :proxyWithTarget :connection] [:id :id :id]]
[[2 :initWithTarget :connection] [:id :id :id]]
[[2 :proxyWithLocal :connection] [:id :id :id]]
[[2 :initWithLocal :connection] [:id :id :id]]
[[1 :setProtocolForProxy] [:void :id]]
[[0 :connectionForProxy] [:id]]
[[1 :notificationCenterForType] [:id :id]]
[[0 :defaultCenter] [:id]]
[[5 :addObserver :selector :name :object :suspensionBehavior] [:void :id :selector :id :id :unsigned-long]]
[[4 :postNotificationName :object :userInfo :deliverImmediately] [:void :id :id :id :signed-char]]
[[4 :postNotificationName :object :userInfo :options] [:void :id :id :id :unsigned-long]]
[[1 :setSuspended] [:void :signed-char]]
[[0 :suspended] [:signed-char]]
[[4 :addObserver :selector :name :object] [:void :id :selector :id :id]]
[[2 :postNotificationName :object] [:void :id :id]]
[[3 :postNotificationName :object :userInfo] [:void :id :id :id]]
[[3 :removeObserver :name :object] [:void :id :id :id]]
[[0 :isBycopy] [:signed-char]]
[[0 :isByref] [:signed-char]]
[[1 :encodePortObject] [:void :id]]
[[0 :decodePortObject] [:id]]
[[0 :connection] [:id]]
[[3 :portCoderWithReceivePort :sendPort :components] [:id :id :id :id]]
[[3 :initWithReceivePort :sendPort :components] [:id :id :id :id]]
[[0 :dispatch] [:void]]
[[3 :initWithSendPort :receivePort :components] [:id :id :id :id]]
[[0 :components] [:id]]
[[0 :receivePort] [:id]]
[[0 :sendPort] [:id]]
[[1 :sendBeforeDate] [:signed-char :id]]
[[0 :msgid] [:unsigned-int]]
[[1 :setMsgid] [:void :unsigned-int]]
[[0 :systemDefaultPortNameServer] [:id]]
[[1 :portForName] [:id :id]]
[[2 :portForName :host] [:id :id :id]]
[[2 :registerPort :name] [:signed-char :id :id]]
[[1 :removePortForName] [:signed-char :id]]
[[0 :sharedInstance] [:id]]
[[1 :portForName] [:id :id]]
[[2 :portForName :host] [:id :id :id]]
[[2 :registerPort :name] [:signed-char :id :id]]
[[1 :servicePortWithName] [:id :id]]
[[0 :sharedInstance] [:id]]
[[1 :portForName] [:id :id]]
[[2 :portForName :host] [:id :id :id]]
[[0 :sharedInstance] [:id]]
[[1 :portForName] [:id :id]]
[[2 :portForName :host] [:id :id :id]]
[[2 :registerPort :name] [:signed-char :id :id]]
[[1 :removePortForName] [:signed-char :id]]
[[3 :portForName :host :nameServerPortNumber] [:id :id :id :unsigned-short]]
[[3 :registerPort :name :nameServerPortNumber] [:signed-char :id :id :unsigned-short]]
[[1 :setDefaultNameServerPortNumber] [:void :unsigned-short]]
[[0 :defaultNameServerPortNumber] [:unsigned-short]]
[[0 :protocol] [:id]]
[[0 :target] [:id]]
[[0 :init] [:id]]
[[1 :setLaunchPath] [:void :id]]
[[1 :setArguments] [:void :id]]
[[1 :setEnvironment] [:void :id]]
[[1 :setCurrentDirectoryPath] [:void :id]]
[[1 :setStandardInput] [:void :id]]
[[1 :setStandardOutput] [:void :id]]
[[1 :setStandardError] [:void :id]]
[[0 :launchPath] [:id]]
[[0 :arguments] [:id]]
[[0 :environment] [:id]]
[[0 :currentDirectoryPath] [:id]]
[[0 :standardInput] [:id]]
[[0 :standardOutput] [:id]]
[[0 :standardError] [:id]]
[[0 :launch] [:void]]
[[0 :interrupt] [:void]]
[[0 :terminate] [:void]]
[[0 :suspend] [:signed-char]]
[[0 :resume] [:signed-char]]
[[0 :processIdentifier] [:int]]
[[0 :isRunning] [:signed-char]]
[[0 :terminationStatus] [:int]]
[[0 :terminationReason] [:long]]
[[1 :initWithKind] [:id :unsigned-long]]
[[2 :initWithKind :options] [:id :unsigned-long :unsigned-long]]
[[0 :document] [:id]]
[[1 :documentWithRootElement] [:id :id]]
[[1 :elementWithName] [:id :id]]
[[2 :elementWithName :URI] [:id :id :id]]
[[2 :elementWithName :stringValue] [:id :id :id]]
[[3 :elementWithName :children :attributes] [:id :id :id :id]]
[[2 :attributeWithName :stringValue] [:id :id :id]]
[[3 :attributeWithName :URI :stringValue] [:id :id :id :id]]
[[2 :namespaceWithName :stringValue] [:id :id :id]]
[[2 :processingInstructionWithName :stringValue] [:id :id :id]]
[[1 :commentWithStringValue] [:id :id]]
[[1 :textWithStringValue] [:id :id]]
[[1 :DTDNodeWithXMLString] [:id :id]]
[[0 :kind] [:unsigned-long]]
[[1 :setName] [:void :id]]
[[0 :name] [:id]]
[[1 :setObjectValue] [:void :id]]
[[0 :objectValue] [:id]]
[[1 :setStringValue] [:void :id]]
[[2 :setStringValue :resolvingEntities] [:void :id :signed-char]]
[[0 :stringValue] [:id]]
[[0 :index] [:unsigned-long]]
[[0 :level] [:unsigned-long]]
[[0 :rootDocument] [:id]]
[[0 :parent] [:id]]
[[0 :childCount] [:unsigned-long]]
[[0 :children] [:id]]
[[1 :childAtIndex] [:id :unsigned-long]]
[[0 :previousSibling] [:id]]
[[0 :nextSibling] [:id]]
[[0 :previousNode] [:id]]
[[0 :nextNode] [:id]]
[[0 :detach] [:void]]
[[0 :XPath] [:id]]
[[0 :localName] [:id]]
[[0 :prefix] [:id]]
[[1 :setURI] [:void :id]]
[[0 :URI] [:id]]
[[1 :localNameForName] [:id :id]]
[[1 :prefixForName] [:id :id]]
[[1 :predefinedNamespaceForPrefix] [:id :id]]
[[0 :description] [:id]]
[[0 :XMLString] [:id]]
[[1 :XMLStringWithOptions] [:id :unsigned-long]]
[[1 :canonicalXMLStringPreservingComments] [:id :signed-char]]
[[1 :setPublicID] [:void :id]]
[[0 :publicID] [:id]]
[[1 :setSystemID] [:void :id]]
[[0 :systemID] [:id]]
[[2 :insertChild :atIndex] [:void :id :unsigned-long]]
[[2 :insertChildren :atIndex] [:void :id :unsigned-long]]
[[1 :removeChildAtIndex] [:void :unsigned-long]]
[[1 :setChildren] [:void :id]]
[[1 :addChild] [:void :id]]
[[2 :replaceChildAtIndex :withNode] [:void :unsigned-long :id]]
[[1 :entityDeclarationForName] [:id :id]]
[[1 :notationDeclarationForName] [:id :id]]
[[1 :elementDeclarationForName] [:id :id]]
[[2 :attributeDeclarationForName :elementName] [:id :id :id]]
[[1 :predefinedEntityDeclarationForName] [:id :id]]
[[1 :initWithXMLString] [:id :id]]
[[1 :setDTDKind] [:void :unsigned-long]]
[[0 :DTDKind] [:unsigned-long]]
[[0 :isExternal] [:signed-char]]
[[1 :setPublicID] [:void :id]]
[[0 :publicID] [:id]]
[[1 :setSystemID] [:void :id]]
[[0 :systemID] [:id]]
[[1 :setNotationName] [:void :id]]
[[0 :notationName] [:id]]
[[1 :initWithRootElement] [:id :id]]
[[1 :replacementClassForClass] [:id :id]]
[[1 :setCharacterEncoding] [:void :id]]
[[0 :characterEncoding] [:id]]
[[1 :setVersion] [:void :id]]
[[0 :version] [:id]]
[[1 :setStandalone] [:void :signed-char]]
[[0 :isStandalone] [:signed-char]]
[[1 :setDocumentContentKind] [:void :unsigned-long]]
[[0 :documentContentKind] [:unsigned-long]]
[[1 :setMIMEType] [:void :id]]
[[0 :MIMEType] [:id]]
[[1 :setDTD] [:void :id]]
[[0 :DTD] [:id]]
[[1 :setRootElement] [:void :id]]
[[0 :rootElement] [:id]]
[[2 :insertChild :atIndex] [:void :id :unsigned-long]]
[[2 :insertChildren :atIndex] [:void :id :unsigned-long]]
[[1 :removeChildAtIndex] [:void :unsigned-long]]
[[1 :setChildren] [:void :id]]
[[1 :addChild] [:void :id]]
[[2 :replaceChildAtIndex :withNode] [:void :unsigned-long :id]]
[[0 :XMLData] [:id]]
[[1 :XMLDataWithOptions] [:id :unsigned-long]]
[[1 :initWithName] [:id :id]]
[[2 :initWithName :URI] [:id :id :id]]
[[2 :initWithName :stringValue] [:id :id :id]]
[[1 :elementsForName] [:id :id]]
[[2 :elementsForLocalName :URI] [:id :id :id]]
[[1 :addAttribute] [:void :id]]
[[1 :removeAttributeForName] [:void :id]]
[[1 :setAttributes] [:void :id]]
[[1 :setAttributesWithDictionary] [:void :id]]
[[0 :attributes] [:id]]
[[1 :attributeForName] [:id :id]]
[[2 :attributeForLocalName :URI] [:id :id :id]]
[[1 :addNamespace] [:void :id]]
[[1 :removeNamespaceForPrefix] [:void :id]]
[[1 :setNamespaces] [:void :id]]
[[0 :namespaces] [:id]]
[[1 :namespaceForPrefix] [:id :id]]
[[1 :resolveNamespaceForName] [:id :id]]
[[1 :resolvePrefixForNamespaceURI] [:id :id]]
[[2 :insertChild :atIndex] [:void :id :unsigned-long]]
[[2 :insertChildren :atIndex] [:void :id :unsigned-long]]
[[1 :removeChildAtIndex] [:void :unsigned-long]]
[[1 :setChildren] [:void :id]]
[[1 :addChild] [:void :id]]
[[2 :replaceChildAtIndex :withNode] [:void :unsigned-long :id]]
[[1 :normalizeAdjacentTextNodesPreservingCDATA] [:void :signed-char]]
[[1 :canResumeDownloadDecodedWithEncodingMIMEType] [:signed-char :id]]
[[2 :initWithRequest :delegate] [:id :id :id]]
[[3 :initWithResumeData :delegate :path] [:id :id :id :id]]
[[0 :cancel] [:void]]
[[2 :setDestination :allowOverwrite] [:void :id :signed-char]]
[[0 :request] [:id]]
[[0 :resumeData] [:id]]
[[1 :setDeletesFileUponFailure] [:void :signed-char]]
[[0 :deletesFileUponFailure] [:signed-char]]
[[0 :transform] [:id]]
[[1 :initWithTransform] [:id :id]]
[[2 :translateXBy :yBy] [:void :double :double]]
[[1 :rotateByDegrees] [:void :double]]
[[1 :rotateByRadians] [:void :double]]
[[1 :scaleBy] [:void :double]]
[[2 :scaleXBy :yBy] [:void :double :double]]
[[0 :invert] [:void]]
[[1 :appendTransform] [:void :id]]
[[1 :prependTransform] [:void :id]]
[[0 :nullDescriptor] [:id]]
[[2 :descriptorWithDescriptorType :data] [:id :unsigned-int :id]]
[[1 :descriptorWithBoolean] [:id :unsigned-char]]
[[1 :descriptorWithEnumCode] [:id :unsigned-int]]
[[1 :descriptorWithInt32] [:id :int]]
[[1 :descriptorWithTypeCode] [:id :unsigned-int]]
[[1 :descriptorWithString] [:id :id]]
[[5 :appleEventWithEventClass :eventID :targetDescriptor :returnID :transactionID] [:id :unsigned-int :unsigned-int :id :short :int]]
[[0 :listDescriptor] [:id]]
[[0 :recordDescriptor] [:id]]
[[2 :initWithDescriptorType :data] [:id :unsigned-int :id]]
[[5 :initWithEventClass :eventID :targetDescriptor :returnID :transactionID] [:id :unsigned-int :unsigned-int :id :short :int]]
[[0 :initListDescriptor] [:id]]
[[0 :initRecordDescriptor] [:id]]
[[0 :descriptorType] [:unsigned-int]]
[[0 :data] [:id]]
[[0 :booleanValue] [:unsigned-char]]
[[0 :enumCodeValue] [:unsigned-int]]
[[0 :int32Value] [:int]]
[[0 :typeCodeValue] [:unsigned-int]]
[[0 :stringValue] [:id]]
[[0 :eventClass] [:unsigned-int]]
[[0 :eventID] [:unsigned-int]]
[[0 :returnID] [:short]]
[[0 :transactionID] [:int]]
[[2 :setParamDescriptor :forKeyword] [:void :id :unsigned-int]]
[[1 :paramDescriptorForKeyword] [:id :unsigned-int]]
[[1 :removeParamDescriptorWithKeyword] [:void :unsigned-int]]
[[2 :setAttributeDescriptor :forKeyword] [:void :id :unsigned-int]]
[[1 :attributeDescriptorForKeyword] [:id :unsigned-int]]
[[0 :numberOfItems] [:long]]
[[2 :insertDescriptor :atIndex] [:void :id :long]]
[[1 :descriptorAtIndex] [:id :long]]
[[1 :removeDescriptorAtIndex] [:void :long]]
[[2 :setDescriptor :forKeyword] [:void :id :unsigned-int]]
[[1 :descriptorForKeyword] [:id :unsigned-int]]
[[1 :removeDescriptorWithKeyword] [:void :unsigned-int]]
[[1 :keywordForDescriptorAtIndex] [:unsigned-int :long]]
[[1 :coerceToDescriptorType] [:id :unsigned-int]]
[[0 :sharedAppleEventManager] [:id]]
[[4 :setEventHandler :andSelector :forEventClass :andEventID] [:void :id :selector :unsigned-int :unsigned-int]]
[[2 :removeEventHandlerForEventClass :andEventID] [:void :unsigned-int :unsigned-int]]
[[0 :currentAppleEvent] [:id]]
[[0 :currentReplyAppleEvent] [:id]]
[[1 :initWithSource] [:id :id]]
[[0 :source] [:id]]
[[0 :isCompiled] [:signed-char]]
[[2 :registerClassDescription :forClass] [:void :id :id]]
[[0 :invalidateClassDescriptionCache] [:void]]
[[1 :classDescriptionForClass] [:id :id]]
[[0 :attributeKeys] [:id]]
[[0 :toOneRelationshipKeys] [:id]]
[[0 :toManyRelationshipKeys] [:id]]
[[1 :inverseForRelationshipKey] [:id :id]]
[[1 :lockWithPath] [:id :id]]
[[1 :initWithPath] [:id :id]]
[[0 :tryLock] [:signed-char]]
[[0 :unlock] [:void]]
[[0 :breakLock] [:void]]
[[0 :lockDate] [:id]]
[[0 :defaultCollector] [:id]]
[[0 :isCollecting] [:signed-char]]
[[0 :disable] [:void]]
[[0 :enable] [:void]]
[[0 :isEnabled] [:signed-char]]
[[0 :collectIfNeeded] [:void]]
[[0 :collectExhaustively] [:void]]
[[0 :currentHost] [:id]]
[[1 :hostWithName] [:id :id]]
[[1 :hostWithAddress] [:id :id]]
[[1 :isEqualToHost] [:signed-char :id]]
[[0 :name] [:id]]
[[0 :names] [:id]]
[[0 :address] [:id]]
[[0 :addresses] [:id]]
[[0 :localizedName] [:id]]
[[1 :setHostCacheEnabled] [:void :signed-char]]
[[0 :isHostCacheEnabled] [:signed-char]]
[[0 :flushHostCache] [:void]]
[[1 :classDescriptionForClass] [:id :id]]
[[3 :initWithSuiteName :className :dictionary] [:id :id :id :id]]
[[0 :suiteName] [:id]]
[[0 :className] [:id]]
[[0 :implementationClassName] [:id]]
[[0 :superclassDescription] [:id]]
[[0 :appleEventCode] [:unsigned-int]]
[[1 :matchesAppleEventCode] [:signed-char :unsigned-int]]
[[1 :supportsCommand] [:signed-char :id]]
[[1 :selectorForCommand] [:selector :id]]
[[1 :typeForKey] [:id :id]]
[[1 :classDescriptionForKey] [:id :id]]
[[1 :appleEventCodeForKey] [:unsigned-int :id]]
[[1 :keyWithAppleEventCode] [:id :unsigned-int]]
[[0 :defaultSubcontainerAttributeKey] [:id]]
[[1 :isLocationRequiredToCreateForKey] [:signed-char :id]]
[[1 :hasPropertyForKey] [:signed-char :id]]
[[1 :hasOrderedToManyRelationshipForKey] [:signed-char :id]]
[[1 :hasReadablePropertyForKey] [:signed-char :id]]
[[1 :hasWritablePropertyForKey] [:signed-char :id]]
[[0 :sharedCoercionHandler] [:id]]
[[2 :coerceValue :toClass] [:id :id :id]]
[[4 :registerCoercer :selector :toConvertFromClass :toClass] [:void :id :selector :id :id]]
[[1 :initWithCommandDescription] [:id :id]]
[[0 :commandDescription] [:id]]
[[1 :setDirectParameter] [:void :id]]
[[0 :directParameter] [:id]]
[[1 :setReceiversSpecifier] [:void :id]]
[[0 :receiversSpecifier] [:id]]
[[0 :evaluatedReceivers] [:id]]
[[1 :setArguments] [:void :id]]
[[0 :arguments] [:id]]
[[0 :evaluatedArguments] [:id]]
[[0 :isWellFormed] [:signed-char]]
[[0 :performDefaultImplementation] [:id]]
[[0 :executeCommand] [:id]]
[[1 :setScriptErrorNumber] [:void :int]]
[[1 :setScriptErrorOffendingObjectDescriptor] [:void :id]]
[[1 :setScriptErrorExpectedTypeDescriptor] [:void :id]]
[[1 :setScriptErrorString] [:void :id]]
[[0 :scriptErrorNumber] [:int]]
[[0 :scriptErrorOffendingObjectDescriptor] [:id]]
[[0 :scriptErrorExpectedTypeDescriptor] [:id]]
[[0 :scriptErrorString] [:id]]
[[0 :currentCommand] [:id]]
[[0 :appleEvent] [:id]]
[[0 :suspendExecution] [:void]]
[[1 :resumeExecutionWithResult] [:void :id]]
[[3 :initWithSuiteName :commandName :dictionary] [:id :id :id :id]]
[[0 :suiteName] [:id]]
[[0 :commandName] [:id]]
[[0 :appleEventClassCode] [:unsigned-int]]
[[0 :appleEventCode] [:unsigned-int]]
[[0 :commandClassName] [:id]]
[[0 :returnType] [:id]]
[[0 :appleEventCodeForReturnType] [:unsigned-int]]
[[0 :argumentNames] [:id]]
[[1 :typeForArgumentWithName] [:id :id]]
[[1 :appleEventCodeForArgumentWithName] [:unsigned-int :id]]
[[1 :isOptionalArgumentWithName] [:signed-char :id]]
[[0 :createCommandInstance] [:id]]
[[0 :sharedScriptExecutionContext] [:id]]
[[0 :topLevelObject] [:id]]
[[1 :setTopLevelObject] [:void :id]]
[[0 :objectBeingTested] [:id]]
[[1 :setObjectBeingTested] [:void :id]]
[[0 :rangeContainerObject] [:id]]
[[1 :setRangeContainerObject] [:void :id]]
[[1 :objectSpecifierWithDescriptor] [:id :id]]
[[2 :initWithContainerSpecifier :key] [:id :id :id]]
[[3 :initWithContainerClassDescription :containerSpecifier :key] [:id :id :id :id]]
[[0 :childSpecifier] [:id]]
[[1 :setChildSpecifier] [:void :id]]
[[0 :containerSpecifier] [:id]]
[[1 :setContainerSpecifier] [:void :id]]
[[0 :containerIsObjectBeingTested] [:signed-char]]
[[1 :setContainerIsObjectBeingTested] [:void :signed-char]]
[[0 :containerIsRangeContainerObject] [:signed-char]]
[[1 :setContainerIsRangeContainerObject] [:void :signed-char]]
[[0 :key] [:id]]
[[1 :setKey] [:void :id]]
[[0 :containerClassDescription] [:id]]
[[1 :setContainerClassDescription] [:void :id]]
[[0 :keyClassDescription] [:id]]
[[1 :objectsByEvaluatingWithContainers] [:id :id]]
[[0 :objectsByEvaluatingSpecifier] [:id]]
[[0 :evaluationErrorNumber] [:long]]
[[1 :setEvaluationErrorNumber] [:void :long]]
[[0 :evaluationErrorSpecifier] [:id]]
[[0 :descriptor] [:id]]
[[4 :initWithContainerClassDescription :containerSpecifier :key :index] [:id :id :id :id :long]]
[[0 :index] [:long]]
[[1 :setIndex] [:void :long]]
[[4 :initWithContainerClassDescription :containerSpecifier :key :name] [:id :id :id :id :id]]
[[0 :name] [:id]]
[[1 :setName] [:void :id]]
[[2 :initWithPosition :objectSpecifier] [:id :unsigned-long :id]]
[[0 :position] [:unsigned-long]]
[[0 :objectSpecifier] [:id]]
[[1 :setInsertionClassDescription] [:void :id]]
[[0 :evaluate] [:void]]
[[0 :insertionContainer] [:id]]
[[0 :insertionKey] [:id]]
[[0 :insertionIndex] [:long]]
[[0 :insertionReplaces] [:signed-char]]
[[5 :initWithContainerClassDescription :containerSpecifier :key :startSpecifier :endSpecifier] [:id :id :id :id :id :id]]
[[0 :startSpecifier] [:id]]
[[1 :setStartSpecifier] [:void :id]]
[[0 :endSpecifier] [:id]]
[[1 :setEndSpecifier] [:void :id]]
[[5 :initWithContainerClassDescription :containerSpecifier :key :relativePosition :baseSpecifier] [:id :id :id :id :unsigned-long :id]]
[[0 :relativePosition] [:unsigned-long]]
[[1 :setRelativePosition] [:void :unsigned-long]]
[[0 :baseSpecifier] [:id]]
[[1 :setBaseSpecifier] [:void :id]]
[[4 :initWithContainerClassDescription :containerSpecifier :key :uniqueID] [:id :id :id :id :id]]
[[0 :uniqueID] [:id]]
[[1 :setUniqueID] [:void :id]]
[[4 :initWithContainerClassDescription :containerSpecifier :key :test] [:id :id :id :id :id]]
[[0 :test] [:id]]
[[1 :setTest] [:void :id]]
[[0 :startSubelementIdentifier] [:unsigned-long]]
[[1 :setStartSubelementIdentifier] [:void :unsigned-long]]
[[0 :startSubelementIndex] [:long]]
[[1 :setStartSubelementIndex] [:void :long]]
[[0 :endSubelementIdentifier] [:unsigned-long]]
[[1 :setEndSubelementIdentifier] [:void :unsigned-long]]
[[0 :endSubelementIndex] [:long]]
[[1 :setEndSubelementIndex] [:void :long]]
[[1 :setReceiversSpecifier] [:void :id]]
[[0 :keySpecifier] [:id]]
[[0 :saveOptions] [:unsigned-long]]
[[0 :createClassDescription] [:id]]
[[0 :resolvedKeyDictionary] [:id]]
[[1 :setReceiversSpecifier] [:void :id]]
[[0 :keySpecifier] [:id]]
[[1 :setReceiversSpecifier] [:void :id]]
[[0 :keySpecifier] [:id]]
[[0 :saveOptions] [:unsigned-long]]
[[1 :setReceiversSpecifier] [:void :id]]
[[0 :keySpecifier] [:id]]
[[0 :sharedScriptSuiteRegistry] [:id]]
[[1 :setSharedScriptSuiteRegistry] [:void :id]]
[[1 :loadSuitesFromBundle] [:void :id]]
[[2 :loadSuiteWithDictionary :fromBundle] [:void :id :id]]
[[1 :registerClassDescription] [:void :id]]
[[1 :registerCommandDescription] [:void :id]]
[[0 :suiteNames] [:id]]
[[1 :appleEventCodeForSuite] [:unsigned-int :id]]
[[1 :bundleForSuite] [:id :id]]
[[1 :classDescriptionsInSuite] [:id :id]]
[[1 :commandDescriptionsInSuite] [:id :id]]
[[1 :suiteForAppleEventCode] [:id :unsigned-int]]
[[1 :classDescriptionWithAppleEventCode] [:id :unsigned-int]]
[[2 :commandDescriptionWithAppleEventClass :andAppleEventCode] [:id :unsigned-int :unsigned-int]]
[[1 :aeteResource] [:id :id]]
[[0 :isTrue] [:signed-char]]
[[1 :initAndTestWithTests] [:id :id]]
[[1 :initOrTestWithTests] [:id :id]]
[[1 :initNotTestWithTest] [:id :id]]
[[3 :initWithObjectSpecifier :comparisonOperator :testObject] [:id :id :unsigned-long :id]]
[[1 :setDelegate] [:void :id]]
[[0 :delegate] [:id]]
[[2 :registerLanguage :byVendor] [:signed-char :id :id]]
[[2 :isWordInUserDictionaries :caseSensitive] [:signed-char :id :signed-char]]
[[0 :run] [:void]]
[[0 :title] [:id]]
[[1 :setTitle] [:void :id]]
[[0 :subtitle] [:id]]
[[1 :setSubtitle] [:void :id]]
[[0 :informativeText] [:id]]
[[1 :setInformativeText] [:void :id]]
[[0 :actionButtonTitle] [:id]]
[[1 :setActionButtonTitle] [:void :id]]
[[0 :userInfo] [:id]]
[[1 :setUserInfo] [:void :id]]
[[0 :deliveryDate] [:id]]
[[1 :setDeliveryDate] [:void :id]]
[[0 :deliveryTimeZone] [:id]]
[[1 :setDeliveryTimeZone] [:void :id]]
[[0 :deliveryRepeatInterval] [:id]]
[[1 :setDeliveryRepeatInterval] [:void :id]]
[[0 :actualDeliveryDate] [:id]]
[[0 :isPresented] [:signed-char]]
[[0 :isRemote] [:signed-char]]
[[0 :soundName] [:id]]
[[1 :setSoundName] [:void :id]]
[[0 :hasActionButton] [:signed-char]]
[[1 :setHasActionButton] [:void :signed-char]]
[[0 :activationType] [:long]]
[[0 :otherButtonTitle] [:id]]
[[1 :setOtherButtonTitle] [:void :id]]
[[0 :defaultUserNotificationCenter] [:id]]
[[1 :scheduleNotification] [:void :id]]
[[1 :removeScheduledNotification] [:void :id]]
[[1 :deliverNotification] [:void :id]]
[[1 :removeDeliveredNotification] [:void :id]]
[[0 :removeAllDeliveredNotifications] [:void]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[0 :scheduledNotifications] [:id]]
[[1 :setScheduledNotifications] [:void :id]]
[[0 :deliveredNotifications] [:id]]
[[0 :scriptURL] [:id]]
[[0 :standardInput] [:id]]
[[1 :setStandardInput] [:void :id]]
[[0 :standardOutput] [:id]]
[[1 :setStandardOutput] [:void :id]]
[[0 :standardError] [:id]]
[[1 :setStandardError] [:void :id]]
[[0 :variables] [:id]]
[[1 :setVariables] [:void :id]]
[[1 :initWithServiceName] [:id :id]]
[[2 :initWithMachServiceName :options] [:id :id :unsigned-long]]
[[1 :initWithListenerEndpoint] [:id :id]]
[[0 :remoteObjectProxy] [:id]]
[[0 :resume] [:void]]
[[0 :suspend] [:void]]
[[0 :invalidate] [:void]]
[[0 :serviceName] [:id]]
[[0 :endpoint] [:id]]
[[0 :exportedInterface] [:id]]
[[1 :setExportedInterface] [:void :id]]
[[0 :exportedObject] [:id]]
[[1 :setExportedObject] [:void :id]]
[[0 :remoteObjectInterface] [:id]]
[[1 :setRemoteObjectInterface] [:void :id]]
[[0 :auditSessionIdentifier] [:int]]
[[0 :processIdentifier] [:int]]
[[0 :effectiveUserIdentifier] [:unsigned-int]]
[[0 :effectiveGroupIdentifier] [:unsigned-int]]
[[0 :serviceListener] [:id]]
[[0 :anonymousListener] [:id]]
[[1 :initWithMachServiceName] [:id :id]]
[[0 :endpoint] [:id]]
[[0 :resume] [:void]]
[[0 :suspend] [:void]]
[[0 :invalidate] [:void]]
[[0 :delegate] [:id]]
[[1 :setDelegate] [:void :id]]
[[1 :interfaceWithProtocol] [:id :id]]
[[4 :setClasses :forSelector :argumentIndex :ofReply] [:void :id :selector :unsigned-long :signed-char]]
[[3 :classesForSelector :argumentIndex :ofReply] [:id :selector :unsigned-long :signed-char]]
[[4 :setInterface :forSelector :argumentIndex :ofReply] [:void :id :selector :unsigned-long :signed-char]]
[[3 :interfaceForSelector :argumentIndex :ofReply] [:id :selector :unsigned-long :signed-char]]
[[0 :protocol] [:id]]
[[1 :setProtocol] [:void :id]]
]
